<?php
/*****************************************************************************
 * Theis Playlist Manager -- An interactive web application for creating,    *
 * editing, and publishing radio playlists.                                  *
 *                                                                           *
 * Copyright (C) 2003  Aaron Forrest                                         *
 *                                                                           *
 * This program is free software; you can redistribute it and/or             *
 * modify it under the terms of the GNU General Public License               *
 * as published by the Free Software Foundation; either version 2            *
 * of the License, or (at your option) any later version.                    *
 *                                                                           *
 * This program is distributed in the hope that it will be useful,           *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of            *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             *
 * GNU General Public License for more details.                              *
 *                                                                           *
 * You should have received a copy of the GNU General Public License         *
 * along with this program; if not, write to the Free Software               *
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.*
 *****************************************************************************/

 // configuration script for Theis Playlist Manager

/****************************
 *   	FUNCTIONS           *
 ****************************/

function writeConfigFile($file, $arr)	{
	// build file contents
	$str = "<?php

/********************************************************************
 *  This is the configuration file that all PHP files should include.
 *  Auto-generated by configure.php.  Edit at your own risk
 ********************************************************************/

/* URL of root, eliminating relative URLs */
define(\"__HOST__\",\"".rtrim($arr[host],"/")."/\");
define(\"__ROOT__\",__HOST__.\"".trim($arr[root],"/")."/\");

/* these allow for relative file includes */
define(\"__BASE__\",dirname(__FILE__).\"/\");
define(\"__CLASSBASE__\",__BASE__.\"classes/\");

/* database configuration stuff */
define(\"__DBUSER__\",\"$arr[dbuser]\");
define(\"__DBPASSWORD__\",\"$arr[dbpassword]\");
define(\"__DBNAME__\",\"$arr[dbname]\");
define(\"__DBHOST__\",\"$arr[dbhost]\");

/* include \"importer\" for including classes */
include(__CLASSBASE__.\"importer.php\");

/* Bug reports go here */
define(\"__BUGREPORTS__\", \"bugs@ultramoderne.net\");

/* Host identification stuff */
define(\"__STATION__\", \"$arr[station]\");
define(\"__REAL__\", \"$arr[real]\");
define(\"__WMP56__\", \"$arr[wmp56]\");
define(\"__WMP100__\", \"$arr[wmp100]\");
define(\"__HOMEPAGE__\", \"$arr[homepage]\");
define(\"__ETAIL_LINK__\", \"$arr[etail_link]\");
define(\"__ETAIL_ARTIST__\", \"$arr[etail_artist]\");
define(\"__ETAIL_ALBUM__\", \"$arr[etail_album]\");
define(\"__ETAIL_LABEL__\", \"$arr[etail_label]\");
?>";
	if ( is_writable($file) )	{
		$f = fopen($file, 'w+');
		fwrite( $f, $str )
			or die("file unable to be written");
		print "Your configuration file has been written. You may need to <a href=\"configure.php\">repeat</a> this process for your other config file. When finished, please copy the contents of the \"playlist/\" and/or \"world/\" folders to the place you want them on your server.\n";
		fclose($f);
		exit;
	}
	else
		print "The file $file is not writeable.  Please check permissions\n";
}

function loginScreen($message="")	{
	print "<html>
			<head><title>tpmConfig</title></head>
			<body>\n";
	print (($message != "") ? "<b>$message</b><br>\n" : "");
	print "<h3>Enter relative path to old config.inc.php file directory</h3>
			<p>
			You must run this configuration once for each config file.
			[usually in playlist/lib and world/].  Permissions must be set
			so that the user that your webserver runs as [under redhat,
			'nobody', under debian, 'www-data'] is owner or at least has write
			permissions for the files you want to alter. If these files do not
			yet, create them before running this script.<br>\n
			WARNING: running this script will totally overwrite your old config
			files.  Back them up before running the script.
			</p>
			<form method=\"POST\">
			<input type=\"hidden\" name=\"action\" value=\"login\">
			<input type=\"text\" name=\"path\" size=\"50\" value=\"$_POST[path]\">
			<br><input type=\"submit\" value=\"submit\">
			</form>
			</body>
			</html>";
	exit;
}

/****************************
 *          MAIN			*
 ****************************/

// attempt to "login" by looking for the specified file
if ( isset($_POST[action]) && $_POST[action] == "login" )	{
	$message = "";
	if ( ! is_dir($_POST[path]) )	{
		$message .= "Please enter a valid relative path to the directory
						containing your old config.inc.php file.<br>\n";
	}
	$file = rtrim($_POST[path], "/")."/config.inc.php";
	if ( ! file_exists($file) )
		$message .= "There is no config.inc.php in the specified directory.
						<br>\n";
	if ( $message == "" ) { 
	    include("$file");
		$logged_in = true;
	}
	else	{
		$logged_in = false;
		loginScreen($message);
	}

}

// attempt to write configuration files
if ( isset($_POST[action]) && $_POST[action] == "configure" )	{
	$message = "";
	if ( empty($_POST[host]) )
		$message .= "please enter a web address for your TPM host";
	if ( empty($_POST[root]) )
		$message .= "please enter the path to your TPM directory root";
	if ( empty($_POST[dbhost]) )
		$message .= "please enter your database host";
	if ( empty($_POST[dbname]) )
		$message .= "please enter your database's name";
	if ( empty($_POST[dbuser]) )
		$message .= "please enter a username for your database";
	if ( empty($_POST[dbpassword]) )
		$message .= "please enter a password for your database";
	if ( empty($_POST[station]) )
		$message .= "please enter your station's call letters";
	if ($message == "")	{	// all tests passed
		writeConfigFile($_POST[file], $_POST);
	}
}
if ( ! $logged_in )
	loginScreen();

if ( defined("__ROOT__") )
	$rooturl_arr = parse_url(__ROOT__);
?>
<html>
<head>
<title>configuration for Theis Playlist Manager</title>
<?php
if ($message != "")
	print "<b>$message</b><br>\n";
?>
<h1>Theis Playlist Manager Configuration</h1>

<form method="POST">
<input type="hidden" name="action" value="configure">
<input type="hidden" name="path" value="<?=$_POST[path]?>">
<input type="hidden" name="file" value="<?=$file?>">
<input type="hidden" name="logged_in" value="<?=$logged_in?>">
<h3>Information about the host for this program</h3>
<p>
Your web server's address:<br>
<input type="text" value="<?=((defined("__HOST__"))?__HOST__:"");?>" name="host" size="50">
</p>

<p>
Path to directory root:<br>
<input type="text" value="<?=ltrim($rooturl_arr[path],"/")?>" name="root" size="50">
</p>

<p>
Database host:<br>
<input type="text" value="<?=((defined("__DBHOST__"))?__DBHOST__:"");?>" name="dbhost">
</p>

<p>
Database name:<br>
<input type="text" value="<?=((defined("__DBNAME__"))?__DBNAME__:"");?>" name="dbname">
</p>

<p>
Database username:<br>
<input type="text" value="<?=((defined("__DBUSER__"))?__DBUSER__:"");?>" name="dbuser">
</p>

<p>
Database password:<br>
<input type="text" value="<?=((defined("__DBPASSWORD__"))?__DBPASSWORD__:"");?>" name="dbpassword">
</p>

<h3>Information about your station</h3>
<p>
Call letters:<br>
<input type="text" value="<?=((defined("__STATION__"))?__STATION__:"");?>" name="station">
</p>

<p>
Realaudio link:<br>
<input type="text" value="<?=((defined("__REAL__"))?__REAL__:"");?>" name="real" size="50">
</p>

<p>
Windows media player [lo bitrate]:<br>
<input type="text" value="<?=((defined("__WMP56__"))?__WMP56__:"");?>" name="wmp56" size="50">
</p>

<p>
Windows media player [hi bitrate]:<br>
<input type="text" value="<?=((defined("__WMP100__"))?__WMP100__:"");?>" name="wmp100" size="50">
</p>

<p>
Homepage:<br>
<input type="text" value="<?=((defined("__HOMEPAGE__"))?__HOMEPAGE__:"");?>" name="homepage" size="50">
</p>

<p>
All-purpose etailer link:<br>
<input type="text" value="<?=((defined("__ETAIL_LINK__"))?__ETAIL_LINK__:"");?>" name="etail_link" size="50">
</p>

<p>
Etailer search-by-artist link:<br>
<input type="text" value="<?=((defined("__ETAIL_ARTIST__"))?__ETAIL_ARTIST__:"");?>" name="etail_artist" size="50">
</p>

<p>
Etailer search-by-album link:<br>
<input type="text" value="<?=((defined("__ETAIL_ALBUM__"))?__ETAIL_ALBUM__:"");?>" name="etail_album" size="50">
</p>

<p>
Etailer search-by-label link:<br>
<input type="text" value="<?=((defined("__ETAIL_LABEL__"))?__ETAIL_LABEL__:"");?>" name="etail_label" size="50">
</p>

<input type="submit" value="configure">
<input type="reset">
</form>
