<!-- Theis Playlist Manager admin navigation bar -->
<table width='100%'>
 <tr><td class='text'>
  <a href="adminmenu.php">main menu</a> |
  <a href="adduser.php">edit user list</a> |
  <a href="top30.php">top 30</a> |
  <a href="manageschedules.php">schedule manager</a> |
  <a href="plmover.php">playlist admin</a> |
  <a href="dbsearch.php">search database</a> |
  <a href="passwd.php">change password</a> |
  <a href="../lib/logout.php">logout</a>
 </td><td class='none' align='right'>
<a href='#' onClick="window.open('../lib/reportbug.php','bug_window','width=500,height=300')">
		<b>send bug report</b></a>
 </td></tr>
</table>
<p>
