<?php
// $Id: manageschedules.php,v 1.5 2004/01/09 03:32:31 admin Exp $
/*****************************************************************************
* Theis Playlist Manager -- An interactive web application for creating,     *
* editing, and publishing radio playlists.                                   *
*                                                                            *
* Copyright (C) 2003  Aaron Forrest                                          *
*                                                                            *
* This program is free software; you can redistribute it and/or              *
* modify it under the terms of the GNU General Public License                *
* as published by the Free Software Foundation; either version 2             *
* of the License, or (at your option) any later version.                     *
*                                                                            *
* This program is distributed in the hope that it will be useful,            *
* but WITHOUT ANY WARRANTY; without even the implied warranty of             *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              *
* GNU General Public License for more details.                               *
*                                                                            *
* You should have received a copy of the GNU General Public License          *
* along with this program; if not, write to the Free Software                *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.*
*****************************************************************************/
/* page for choosing schedule-managing tasks */


include("../lib/config.inc.php");
include("../lib/dblib.inc.php");
include("../lib/usrlib.inc.php");

checkAdminUser();

?>
<html>
<!-- This page generated by Theis Playlist Manager -->
<head>
<title>Schedule Manager</title>
<link href="../css/wprb.css" rel="stylesheet" type="text/css">
</head>
<body>
<? include("adminnav.inc"); ?>
<h2>&nbsp;&nbsp;&nbsp;&nbsp;Schedule Manager</h2>

<ul>
	<li><span class='text'><a href='schedule_new.php'>new schedule</a></span><br>
	<li><span class='text'><a href='schedule_list.php'>edit schedule</a></span><br>
	<li><span class='text'><a href='adminmenu.php'>back to main menu</a></span><br>
</ul>
</body>
</html>
