<?php
// $Id: plmover_djnames.php,v 1.2 2004/10/16 03:09:10 admin Exp $
/*****************************************************************************
* Theis Playlist Manager -- An interactive web application for creating,     *
* editing, and publishing radio playlists.                                   *
*                                                                            *
* Copyright (C) 2003  Aaron Forrest                                          *
*                                                                            *
* This program is free software; you can redistribute it and/or              *
* modify it under the terms of the GNU General Public License                *
* as published by the Free Software Foundation; either version 2             *
* of the License, or (at your option) any later version.                     *
*                                                                            *
* This program is distributed in the hope that it will be useful,            *
* but WITHOUT ANY WARRANTY; without even the implied warranty of             *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              *
* GNU General Public License for more details.                               *
*                                                                            *
* You should have received a copy of the GNU General Public License          *
* along with this program; if not, write to the Free Software                *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.*
*****************************************************************************/

include("../lib/config.inc.php");
include("../lib/dblib.inc.php");
include("../lib/usrlib.inc.php");

import("org/wprb/Users.php");
import("org/wprb/user.php");

checkAdminUser();

$users = new Users();
$users->load(null);

$users->reset()

?>
<html>
<!-- This page generated by Theis Playlist Manager -->
<head>
<link href="../css/wprb.css" rel='styleSheet' type="text/css" />
</head>
<body bgcolor="#DDDDEE">
<br>
<b class="black">&nbsp;dj list</b>
<div class="text">
<?php
while ( $users->hasNext() )	{
	$row = $users->next();
	print "&nbsp;&nbsp;+<a class=\"black\" href=\"plmover_djnames.php?expand=$row->ID\">$row->login</a><br />\n";

	if (isset($_GET[expand]) && $row->ID == $_GET[expand])	{
		$dj = new User ($row->ID);
		$playlists = $dj->getPlaylists();
		$playlists->reset();
		while ($playlists->hasNext())	{
			$pl_row = $playlists->next();
			print "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
			print "<a class='tree' href=\"plmover_mover.php?show_id=$pl_row->ID\" target=\"mover\">";
			print date('l, F j, Y, H:i', $pl_row->starttime);
			print "</a><br />\n";
		}
	}
}
?>
</div>
</body>
</html>
