<?php
// $Id: plmover_navbar.php,v 1.2 2004/10/16 03:09:10 admin Exp $
/*****************************************************************************
* Theis Playlist Manager -- An interactive web application for creating,     *
* editing, and publishing radio playlists.                                   *
*                                                                            *
* Copyright (C) 2003  Aaron Forrest                                          *
*                                                                            *
* This program is free software; you can redistribute it and/or              *
* modify it under the terms of the GNU General Public License                *
* as published by the Free Software Foundation; either version 2             *
* of the License, or (at your option) any later version.                     *
*                                                                            *
* This program is distributed in the hope that it will be useful,            *
* but WITHOUT ANY WARRANTY; without even the implied warranty of             *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              *
* GNU General Public License for more details.                               *
*                                                                            *
* You should have received a copy of the GNU General Public License          *
* along with this program; if not, write to the Free Software                *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.*
*****************************************************************************/

include ("../lib/config.inc.php");
include ("../lib/dblib.inc.php");
include ("../lib/usrlib.inc.php");

checkAdminUser ();
?>
<html>
<!-- This page generated by Theis Playlist Manager -->
<head>
<link href="../css/wprb.css" rel="stylesheet" type="text/css">
</head>

<body bgcolor="#DDDDEE">
<table width='100%'>
 <tr><td class='text'>
  <a href="adminmenu.php" target="_parent">main menu</a> |
  <a href="adduser.php" target="_parent">edit user list</a> |
  <a href="top30.php" target="_parent">top 30</a> |
  <a href="manageschedules.php" target="_parent">schedule manager</a> |
  <a href="dbsearch.php" target="_parent">search database</a> |
  <a href="passwd.php" target="_parent">change password</a> |
  <a href="../lib/logout.php" target="_parent">logout</a>
 </td><td class='none' align='right'>
<a href='#' onClick="window.open('../lib/reportbug.php','bug_window','width=500,height=300')">
		<b>send bug report</b></a>
 </td></tr>
</table>
</body>
</html>
