<?php
// $Id: plmover.php,v 1.2 2004/10/16 03:09:10 admin Exp $
/*****************************************************************************
* Theis Playlist Manager -- An interactive web application for creating,     *
* editing, and publishing radio playlists.                                   *
*                                                                            *
* Copyright (C) 2003  Aaron Forrest                                          *
*                                                                            *
* This program is free software; you can redistribute it and/or              *
* modify it under the terms of the GNU General Public License                *
* as published by the Free Software Foundation; either version 2             *
* of the License, or (at your option) any later version.                     *
*                                                                            *
* This program is distributed in the hope that it will be useful,            *
* but WITHOUT ANY WARRANTY; without even the implied warranty of             *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              *
* GNU General Public License for more details.                               *
*                                                                            *
* You should have received a copy of the GNU General Public License          *
* along with this program; if not, write to the Free Software                *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.*
*****************************************************************************/

include ("../lib/config.inc.php");
include ("../lib/dblib.inc.php");
include ("../lib/usrlib.inc.php");

checkAdminUser ();
?>

<html>
<!-- This page generated by Theis Playlist Manager -->
<head>
<title>Theis Playlist Manager</title>
</head>

<frameset rows="25, *" border="1">
	<frame src="plmover_navbar.php" name="navbar" frameborder="1" scrolling="no" marginheight="1" noresize />
	<frameset cols="25%, 75%">
		<frame src="plmover_djnames.php" name="djnames" frameborder="1" marginheight="0" />
		<frame src="" name="mover" frameborder="1"/>
	</frameset>
</frameset>
</html>
