<?php
// $Id: plmover_mover.php,v 1.3 2004/10/16 16:21:52 admin Exp $
/*****************************************************************************
* Theis Playlist Manager -- An interactive web application for creating,     *
* editing, and publishing radio playlists.                                   *
*                                                                            *
* Copyright (C) 2003  Aaron Forrest                                          *
*                                                                            *
* This program is free software; you can redistribute it and/or              *
* modify it under the terms of the GNU General Public License                *
* as published by the Free Software Foundation; either version 2             *
* of the License, or (at your option) any later version.                     *
*                                                                            *
* This program is distributed in the hope that it will be useful,            *
* but WITHOUT ANY WARRANTY; without even the implied warranty of             *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              *
* GNU General Public License for more details.                               *
*                                                                            *
* You should have received a copy of the GNU General Public License          *
* along with this program; if not, write to the Free Software                *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.*
*****************************************************************************/

include ("../lib/config.inc.php");
include ("../lib/dblib.inc.php");
include ("../lib/usrlib.inc.php");

// use the Playlist class
import ("org/wprb/Playlist.php");
import ("org/wprb/user.php");

checkAdminUser ();



$playlist = new Playlist ($_GET['show_id']);
$playlist->getPlaylistInfo ();
$playlistinfo = $playlist->info;

if (isset($_GET['flag']) && $_GET['flag']=="go")	{
	if (isset ($_GET['action']) && $_GET['action']=="Delete")	{
		$playlist->delete();
		exit;
	}
	if (isset ($_GET['action']) && $_GET['action']=="Transfer")	{
		$playlist->changeOwner ($_GET['operand']);
	}
}

$date = date('l, F j, Y, H:i', $playlistinfo->starttime);

?>

<html>
<!-- This page generated by Theis Playlist Manager -->
<head>
<link href="../css/wprb.css" rel="stylesheet" type="text/css">

<script language="Javascript">
function deleteWarning ()	{
	if (document.mover_form.action.value == "Delete")	{
		return window.confirm ("Delete this playlist?");
	}
}
</script>
</head>
<body>
<?php
(! empty($playlistinfo->title)) ? print "<h2>$playlistinfo->title</h2><h3>$playlistinfo->subtitle</h3>\n" : 
print "<h2>$playlistinfo->genre</h2>";
print "<h3> with $playlistinfo->djname</h3>\n";
$end = $playlistinfo->starttime + $playlistinfo->duration*60*60;
print "<span class='text'>";
print date('l, F j, Y', $playlistinfo->starttime)."<br>\n";
print date('H:i', $playlistinfo->starttime)." to ".date('H:i', $end);
(! empty($playlistinfo->genre)) ? print "<br>$playlistinfo->othergenre<br>\n":''; 
print "</span>";
?>

<table><tr>
<?php

if ( $playlistinfo->genre != "Classical" )
	$headers = array("artist"=>"Artist", "song"=>"Song", "album"=>"Album", 
					"label"=>"Label", "comments"=>"Comments", "emph"=>"Emph",
					"request"=>"R", "comp"=>"C");
	else $headers = array("artist"=>"Composer", "song"=>"Piece", 
				"ensemble"=>"Ensemble/<br>Orchestra", "conductor"=>"Conductor", 
				"performer"=>"Soloist/<br>Performer", "label"=>"Label", 
				"comments"=>"Comments", "emph"=>"Recently<br>Released");

foreach ($headers as $header)	{
	print "\t\t<th bgcolor='#DDDDDD'>$header</th>\n";
}
print "\t</tr>\n";

$playlist->reset();

while ($playlist->hasNext())	{
	$row = $playlist->next();
	print "\t<tr>\n";
	
	foreach ($headers as $key=>$header)	{
		if ( $key == "request" || $key == "comp" )	{
			print "\t\t<td bgcolor=\"EEEEEE\" class=\"text\">";
			print (( ! $row->$key) ? "&nbsp;" : $header );
			print "</td>\n";
			continue;
		}
		print "\t\t<td bgcolor=\"EEEEEE\" class=\"text\">".$row->$key."</td>\n";
	}

	print "\t</tr>\n";
}
?>
</table>
<?php
$user = new User ($playlistinfo->userID);
$loginsrow = getRow ("logins", "ID", $user->loginsID, 'i');
?>
<b>Current owner is <?= $loginsrow[1] ?></b>
<p></p>

<table class="outline" bgcolor="#ddddee" cellpadding="3">
 <tr>
  <td>
	<form name="mover_form" method="GET" onSubmit="return deleteWarning();">
	<input type="hidden" name="flag" value="go" />
	<input type="hidden" name="show_id" value="<?= $_GET['show_id'] ?>" />
	<select name="action">
		<option>Action...</option>
		<option>Transfer</option>
		<option>Delete</option>
	</select>
	&nbsp;<b class="black">TO</b>&nbsp;
	<select name="operand">
		<?php
		 writeUsernameOptions();
		?>
	</select>
  </td>
 </tr><tr>
  <td align="right">
   <input type="submit" value="submit" />
  </td>
 </tr>
</table>


</body>
</html>
