<?php
// $Id: printTop30.php,v 1.5 2004/01/09 03:32:31 admin Exp $
/*****************************************************************************
* Theis Playlist Manager -- An interactive web application for creating,     *
* editing, and publishing radio playlists.                                   *
*                                                                            *
* Copyright (C) 2003  Aaron Forrest                                          *
*                                                                            *
* This program is free software; you can redistribute it and/or              *
* modify it under the terms of the GNU General Public License                *
* as published by the Free Software Foundation; either version 2             *
* of the License, or (at your option) any later version.                     *
*                                                                            *
* This program is distributed in the hope that it will be useful,            *
* but WITHOUT ANY WARRANTY; without even the implied warranty of             *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              *
* GNU General Public License for more details.                               *
*                                                                            *
* You should have received a copy of the GNU General Public License          *
* along with this program; if not, write to the Free Software                *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.*
*****************************************************************************/

include("../lib/config.inc.php");
include("../lib/dblib.inc.php");
include("../lib/usrlib.inc.php");

checkAdminUser();

$start = getdate($starttime);
$end = getdate($endtime);

if (isset($flag) && $flag=="send")	{
	$message = "";
	if (empty($form[email]))
		$message .= "You must enter an email address";
	if (! empty($form[email]) && preg_match("/\A\w+(\.\w+)*@(\w+\.)+\w+\Z/", $form[email], $array) == false )
		$message .= "You must enter a valid email address<br>\n";
	if ($message == "")	{
		$subject = "$genre Playlist for $start[mon]/$start[mday]/$start[year] - $end[mon]/$end[mday]/$end[year]";
		mailQueryResults($form[email], $subject, $emailquery, $start, 
				$end, $genre );
	}
}
?>
<html>

<!-- This page generated by Theis Playlist Manager -->
<head>
<title>Top plays for <?= "$start[mon]/$start[mday]/$start[year]" ?> - <?= "$end[mon]/$end[mday]/$end[year]" ?></title>
<link href="../css/wprb.css" rel="stylesheet" type="text/css">
</head>
<body>
<?php
include("adminnav.inc");
if ($message != "")
	print "<b>$message</b><br>\n";
print "<h2>Top $genre plays for $start[mon]/$start[mday]/$start[year] - $end[mon]/$end[mday]/$end[year]</h2>";
print "<table width=\"100%\" border=\"0\" cellpadding=\"3\" cellspacing=\"2\">\n";
	print "\t<tr>\n";
	print "\t\t<th align='left' bgcolor=\"#CCCCCC\"><a href='printTop30.php?starttime=$starttime&endtime=$endtime&genre=$genre&emph=$emph&sortby=artist'><b class='black'>Artist</b></a></th>\n";
	print "\t\t<th align='left' bgcolor=\"#CCCCCC\"><a href='printTop30.php?starttime=$starttime&endtime=$endtime&genre=$genre&emph=$emph&sortby=song'><b class='black'>Song</b></a></th>\n";
	print "\t\t<th align='left' bgcolor=\"#CCCCCC\"><a href='printTop30.php?starttime=$starttime&endtime=$endtime&genre=$genre&emph=$emph&sortby=album'><b class='black'>Album</b></a></th>\n";
	print "\t\t<th align='left' bgcolor=\"#CCCCCC\"><a href='printTop30.php?starttime=$starttime&endtime=$endtime&genre=$genre&emph=$emph&sortby=label'><b class='black'>Label</b></a></th>\n";
	print "\t\t<th align='left' bgcolor=\"#CCCCCC\"><a href='printTop30.php?starttime=$starttime&endtime=$endtime&genre=$genre&emph=$emph&sortby=emph'><b class='black'>Emph</b></a></th>\n";
	print "\t\t<th align='left' bgcolor=\"#CCCCCC\"><a href='printTop30.php?starttime=$starttime&endtime=$endtime&genre=$genre&emph=$emph&sortby=comp'><b class='black'>Comp</b></a></th>\n";
	print "\t\t<th align='left' bgcolor=\"#CCCCCC\"><a href='printTop30.php?starttime=$starttime&endtime=$endtime&genre=$genre&emph=$emph&sortby=starttime'><b class='black'>Show Time</b></a></th>\n";
	print "\t\t<th align='left' bgcolor=\"#CCCCCC\"><a href='printTop30.php?starttime=$starttime&endtime=$endtime&genre=$genre&emph=$emph&sortby=djname'><b class='black'>PLayed By</b></a></th>\n";
	print "\t</tr>\n";
if (isset($endtime) && isset($starttime))	{
	$lastquery = printTopPlays($starttime, $endtime, $genre, $emph, $sortby);
}
print "</table>\n";
?>
<hr>

<form method="POST">
<span class='text'>
Email this list to: </span>
<input type="hidden" name="flag" value="send">
<!-- hidden fields provide persistence of variables once send button is clicked -->
<input type="hidden" name="genre" value="<?=$genre?>">
<input type="hidden" name="emailquery" value="<?= $lastquery ?>">
<input type="text" name="form[email]">
<input type="submit" value="send">
</form>

</body>
</html>
