<?php
// $Id: schedule_new.php,v 1.5 2004/01/09 03:32:31 admin Exp $
/*****************************************************************************
* Theis Playlist Manager -- An interactive web application for creating,     *
* editing, and publishing radio playlists.                                   *
*                                                                            *
* Copyright (C) 2003  Aaron Forrest                                          *
*                                                                            *
* This program is free software; you can redistribute it and/or              *
* modify it under the terms of the GNU General Public License                *
* as published by the Free Software Foundation; either version 2             *
* of the License, or (at your option) any later version.                     *
*                                                                            *
* This program is distributed in the hope that it will be useful,            *
* but WITHOUT ANY WARRANTY; without even the implied warranty of             *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              *
* GNU General Public License for more details.                               *
*                                                                            *
* You should have received a copy of the GNU General Public License          *
* along with this program; if not, write to the Free Software                *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.*
*****************************************************************************/

include("../lib/config.inc.php");
include("../lib/dblib.inc.php");
include("../lib/usrlib.inc.php");

import("org/wprb/schedule.php");

checkAdminUser();
$schedule = new Schedule();
if (isset($_POST[action]) && $_POST[action] == create)	{
	$id=$schedule->newSchedule($_POST[season], $_POST[year]);
	header("Location: schedule_edit.php?id=$id");
}
?>

<html>
<!-- This page generated by Theis Playlist Software -->
<head>
<title>Create New Schedule</title>
<link href="../css/wprb.css" rel="StyleSheet" type="text/css">
</head>
<body>
<?php
include("adminnav.inc");

// get current month and year
$current = getdate();

?>
&nbsp;
<p>
<h3>Choose year and season for new schedule</h3>
<form method="POST">
<input type="hidden" name="action" value="create">
<select name='season'>
	<?php writeSeasonOptions($current[month]); ?>
</select>
<select name='year'>
	<option><?= $current[year]-1 ?>
	<option SELECTED><?= $current[year] ?>
	<option><?= $current[year]+1 ?>
</select>
<input type="submit" value="create">
</form>

</body>
</html>
