<?php
// $Id: schedule_line.php,v 1.1 2004/10/16 19:36:27 admin Exp $
/*****************************************************************************
* Theis Playlist Manager -- An interactive web application for creating,     *
* editing, and publishing radio playlists.                                   *
*                                                                            *
* Copyright (C) 2003  Aaron Forrest                                          *
*                                                                            *
* This program is free software; you can redistribute it and/or              *
* modify it under the terms of the GNU General Public License                *
* as published by the Free Software Foundation; either version 2             *
* of the License, or (at your option) any later version.                     *
*                                                                            *
* This program is distributed in the hope that it will be useful,            *
* but WITHOUT ANY WARRANTY; without even the implied warranty of             *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              *
* GNU General Public License for more details.                               *
*                                                                            *
* You should have received a copy of the GNU General Public License          *
* along with this program; if not, write to the Free Software                *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.*
*****************************************************************************/

/* page for editing schedule line */

include("../lib/config.inc.php");
include("../lib/dblib.inc.php");
include("../lib/usrlib.inc.php");

import("org/wprb/schedule.php");

$schedule = new Schedule($_GET[id]);

if (isset ($_POST[action]) && $_POST[action] == "update")	{
	if (empty($_POST[title]))
		$message .= "You must input a title for this show<br>\n";
	(($_POST[startmin] != "00") ? $start=$_POST[starthour]*100+30 : $start=$_POST[starthour]*100);
	(($_POST[endmin] != "00") ? $end=$_POST[endhour]*100+30: $end=$_POST[endhour]*100);
	(($start < 600) ? $start = $start+2400: $start=$start);
	(($end < 600) ? $end = $end + 2400: $end=$end);
	// uncomment if shows should never breach the 6am mark
	// if ( $start >= $end )
	// 	$message .= "End time must be later than start time<br>\n";
	if ( $schedule->checkTimeOverlap($_POST[day], $start, $end) && $schedule->verifyTimeOverlap ($_POST[line_id]))
		$message .= "Time overlaps with another show<br>\n";
	if ($message == "" )	{
		$schedule->updateRow($_POST[line_id], $_POST[dj], $_POST[title], $_POST[day], $start, $end, $_POST[genre]);
		header ("Location: schedule_edit.php?id=$_GET[id]");
	}
}

// get data for this line
$line = null;
$schedule->reset ();
while ($schedule->hasNext ())	{
	$row = $schedule->next ();
	if ($row->ID == $_GET[line_id])	{
		$line = $row;
		break;
	}
}
(($line->start > 2400) ? $line->start = $line->start-2400 : $line);
(($line->end > 2400) ? $line->end = $line->end-2400 : $line);
$starthour = intval($line->start/100);
$startmin = $line->start - ($starthour*100);
(($startmin==0) ? $startmin="00": $startmin);
$endhour = intval($line->end/100);
$endmin = $line->end - ($endhour*100);
(($endmin==0) ? $endmin="00": $endmin);
		
?>

<html>
<!-- This page generated by Theis Playlist Manager -->
<head>
<title>Edit schedule line</title>
<link href="../css/wprb.css" rel="StyleSheet" type="text/css" />
</head>
<body>
<?php
include ("adminnav.inc");

if ($message != "")
	print "<b>$message</b><br />\n";
?>

<h3>Edit schedule line</h3>

<form method='POST'>
<input type="hidden" name="action" value="update" />
<input type="hidden" name="line_id" value="<?=$_GET[line_id]?>" />
<table cellpadding='3'>
	<tr height='20'>
		<th class='text' bgcolor='#DDDDDD' align='left'>User:</th>
		<th class='text' bgcolor='#DDDDDD' align='left'>Show title:</th>
		<th class='text' bgcolor='#DDDDDD' align='left'>Genre:</th>
		<th class='text' bgcolor='#DDDDDD' align='left'>Day: </th>
		<th class='text' bgcolor='#DDDDDD' align='left'>Start time:</th>
		<th class='text' bgcolor='#DDDDDD' align='left'>End time:</th>
	</tr>
	<tr>
		<td bgcolor='#EEEEEE'>
			<select name='dj'>
				<?php writeUsernameOptions(); ?>
			</select>
		</td><td bgcolor='#EEEEEE'>
			<input type="text" name="title" value="<?= stripslashes($line->title) ?>">
		</td><td bgcolor='#EEEEEE'>
			<select name="genre">
				<?php writeGenreOptions($line->genre); ?>
			</select>
		</td><td bgcolor='#EEEEEE'>
			<select name="day">
				<?php writeWeekDayOptions($line->day); ?>
			</select>
		</td><td bgcolor='#EEEEEE'>
			<select name='starthour'>
				<?php writeHourOptions($starthour); ?>
			</select> : 
			<select name="startmin">
				<?php writeMinuteOptions($startmin); ?>
			</select>
		</td><td bgcolor='#EEEEEE'>
			<select name='endhour'>
				<?php writeHourOptions($endhour); ?>
			</select>
			<select name='endmin'>
				<?php writeMinuteOptions($endmin); ?>
			</select>
		</td>
	</tr><tr>
		<td colspan='6'><input type="submit" value="update"></td>
	</tr>
</table>
</form>
<p>
&lt;&lt; <a href="schedule_edit.php?id=<?=$_GET[id]?>">back to schedule</a>
</p>
</body>
</html>

