<?php
// $Id: schedule_edit.php,v 1.9 2004/10/16 19:36:27 admin Exp $
/*****************************************************************************
* Theis Playlist Manager -- An interactive web application for creating,     *
* editing, and publishing radio playlists.                                   *
*                                                                            *
* Copyright (C) 2003  Aaron Forrest                                          *
*                                                                            *
* This program is free software; you can redistribute it and/or              *
* modify it under the terms of the GNU General Public License                *
* as published by the Free Software Foundation; either version 2             *
* of the License, or (at your option) any later version.                     *
*                                                                            *
* This program is distributed in the hope that it will be useful,            *
* but WITHOUT ANY WARRANTY; without even the implied warranty of             *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              *
* GNU General Public License for more details.                               *
*                                                                            *
* You should have received a copy of the GNU General Public License          *
* along with this program; if not, write to the Free Software                *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.*
*****************************************************************************/

include("../lib/config.inc.php");
include("../lib/dblib.inc.php");
include("../lib/usrlib.inc.php");

import("org/wprb/schedule.php");

checkAdminUser();

$schedule = new Schedule($_GET[id]);
$sched_info = $schedule->getScheduleInfo ();

if (isset($_POST[action]) && $_POST[action] = 'manipulate')	{
	if ($_POST[manipulate] == "Delete")	{
		$schedule->deleteRow($_POST[rowID]);
		$schedule->Schedule($id);
	}
	if ($_POST[manipulate] == "Edit")	{
		header ("Location: schedule_line.php?id=$_GET[id]&line_id=$_POST[rowID]");
	}
}
$message = "";
if (isset($_POST[action2]) && $_POST[action2] == 'add')	{
	if (empty($_POST[title]))
		$message .= "You must input a title for this show<br>\n";
	(($_POST[startmin] != "00") ? $start=$_POST[starthour]*100+30 : $start=$_POST[starthour]*100);
	(($_POST[endmin] != "00") ? $end=$_POST[endhour]*100+30: $end=$_POST[endhour]*100);
	(($start < 600) ? $start = $start+2400: $start=$start);
	(($end < 600) ? $end = $end + 2400: $end=$end);
	// uncomment if shows should never breach the 6am mark
	// if ( $start >= $end )
	// 	$message .= "End time must be later than start time<br>\n";
	if ( $schedule->checkTimeOverlap($_POST[day], $start, $end) )
		$message .= "Time overlaps with another show<br>\n";
	if ($message == "" )	{
		$schedule->addRow($_POST[dj], $_POST[title], $_POST[day], $start, $end, $_POST[genre]);
		$schedule->Schedule($id);
	}
}

if (isset($_POST[action3]) && $_POST[action3]="exeunt")	{
	if (! empty($_POST[set_current]))
		$schedule->setCurrent();
	header("Location: manageschedules.php");
}

?>
<html>
<!-- This page generated by Theis Playlist Manager -->
<head>
<title>Edit Schedule</title>
<link href="../css/wprb.css" rel="StyleSheet" type="text/css">
</head>
<body>
<?php
include("adminnav.inc");

if ($message!="")
	print "<b>$message</b><br>\n";
?>
<h3>Edit Schedule - <?= "$sched_info->season $sched_info->year" ?></h3>
<table width=535>

<form method='POST'>
<input type="hidden" name="action" value="manipulate">
<?php
$days = array("sundays", "mondays", "tuesdays", "wednesdays", "thursdays", 
				"fridays", "saturdays" );
// loop through the schedule and print shows in the appropriate spots
for ($i=0; $i<7; $i++)	{
	$schedule->reset();
	print "\t<tr><td  class='table_heading' colspan='3' BGCOLOR='#FF6600' height='14'><tt>  $days[$i]</tt></td></tr>\n";
	while ($schedule->hasNext())	{
		$row = $schedule->next();
		if ( $row->day == $i )	{
			(($row->start > 2400) ? $row->start = $row->start-2400 : $row);
			(($row->end > 2400) ? $row->end = $row->end-2400 : $row);
			$starthour = intval($row->start/100);
			$startmin = $row->start - ($starthour*100);
			(($startmin==0) ? $startmin="00": $startmin);
			$endhour = intval($row->end/100);
			$endmin = $row->end - ($endhour*100);
			(($endmin==0) ? $endmin="00": $endmin);
			
			print "\t<tr height='20'>\n";
			print "\t\t<td class='table_text' bgcolor='#EEEEEE' nowrap>$starthour:$startmin - $endhour:$endmin</td>\n";
			print "\t\t<td class='table_text' bgcolor='#EEEEEE'>".stripslashes($row->title)."</td>\n";
			print "\t\t<td bgcolor='#EEEEEE' align='right' width='60'><input type='checkbox' name='rowID' value='$row->ID'></td>\n";
			print "\t</tr>\n";
		}
	}
	print "<tr><td>&nbsp;</td></tr>\n";
}

?>
	<tr width="535">
		<td colspan="3" align="right">
			<select name="manipulate">
				<option />Edit
				<option />Delete
			</select>
		</td>
	</tr>
	<tr width="535">
		<td colspan="3" align='right'>
			<input type="submit" value="submit">
		</td>
	</tr>
</form>
</table>
<p>
<form method='POST'>
<input type="hidden" name="action2" value="add">
<table cellpadding='3'>
	<tr height='20'>
		<th class='text' bgcolor='#DDDDDD' align='left'>User:</th>
		<th class='text' bgcolor='#DDDDDD' align='left'>Show title:</th>
		<th class='text' bgcolor='#DDDDDD' align='left'>Genre:</th>
		<th class='text' bgcolor='#DDDDDD' align='left'>Day: </th>
		<th class='text' bgcolor='#DDDDDD' align='left'>Start time:</th>
		<th class='text' bgcolor='#DDDDDD' align='left'>End time:</th>
	</tr>
	<tr>
		<td bgcolor='#EEEEEE'>
			<select name='dj'>
				<?php writeUsernameOptions(); ?>
			</select>
		</td><td bgcolor='#EEEEEE'>
			<input type="text" name="title" value="<?= stripslashes($_POST[title]) ?>">
		</td><td bgcolor='#EEEEEE'>
			<select name="genre">
				<?php writeGenreOptions($_POST[genre]); ?>
			</select>
		</td><td bgcolor='#EEEEEE'>
			<select name="day">
				<?php writeWeekDayOptions($_POST[day]); ?>
			</select>
		</td><td bgcolor='#EEEEEE'>
			<select name='starthour'>
				<?php writeHourOptions($_POST[starthour]); ?>
			</select> : 
			<select name="startmin">
				<?php writeMinuteOptions($_POST[startmin]); ?>
			</select>
		</td><td bgcolor='#EEEEEE'>
			<select name='endhour'>
				<?php writeHourOptions($_POST[endhour]); ?>
			</select>
			<select name='endmin'>
				<?php writeMinuteOptions($_POST[endmin]); ?>
			</select>
		</td>
	</tr><tr>
		<td colspan='6' align='right'><input type="submit" value="insert"></td>
	</tr>
</table>
</form>

<p>
<b class='text'>End editing session</b>
<form method="POST">
<input type="hidden" name="action3" value="exeunt">
<input type="submit" name="set_current" value="set as current">
<input type="submit" value="don't set current">
</form>
</body>
</html>
