<?php
// $Id: endedit.php,v 1.6 2004/08/31 15:20:38 admin Exp $
/******************************************************************************
 * Theis Playlist Manager -- An interactive web application for creating,     *
 * editing, and publishing radio playlists.                                   *
 *                                                                            *
 * Copyright (C) 2003  Aaron Forrest                                          *
 *                                                                            *
 * This program is free software; you can redistribute it and/or              *
 * modify it under the terms of the GNU General Public License                *
 * as published by the Free Software Foundation; either version 2             *
 * of the License, or (at your option) any later version.                     *
 *                                                                            *
 * This program is distributed in the hope that it will be useful,            *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of             *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              *
 * GNU General Public License for more details.                               *
 *                                                                            *
 * You should have received a copy of the GNU General Public License          *
 * along with this program; if not, write to the Free Software                *
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.*
 *****************************************************************************/

include("../lib/config.inc.php");
include("../lib/dblib.inc.php");
include("../lib/usrlib.inc.php");

/* we are going to use the playlist class */
import("org/wprb/Playlist.php");
import("org/wprb/user.php");

checkUser();
checkGuestUser();

// perform form actions
if (isset($form[confirm]))
	{
	// destroy playlist session
	header( "Location: usermenu.php" );
	}
if (isset($form[reject]))
	{
	header( "Location: editplaylist.php?show_id=$show_id" );
	}

/* now lets create an instance of the class (get playlist with id=5) *
 * then get basic information about that playlist 					 */
$playlist = new Playlist($_GET[show_id]);
$playlist->getPlaylistInfo();
$playlistinfo = $playlist->info;


/* get user info for this playlist */
$user = new User($playlistinfo->userID);
$userinfo = $user->returnUserInfo();
$colors = array("textcolor"=>$userinfo[textcolor], "tabletext"=>$userinfo[tabletext]);

$date = date('l, F j, Y, H:i', $playlistinfo->starttime);

?>

<html>
<!-- This page generated by Theis Playlist Manager -->
<head>
<title>End show</title>
<style type="text/css">
@import url(../css/wprb.css);
h2	{ color:#<?=$userinfo[textcolor]?> }
h3 { color: #<?=$userinfo[textcolor]?>; line-height:.5 }
.text { color: #<?=$userinfo[textcolor]?> }
a { color: #<?=$userinfo[textcolor]?> }
b { color: #<?=$userinfo[textcolor]?> }
.black { color: #<?=$userinfo[textcolor]?> }
</style>
</head>

<body bgcolor="#<?=$userinfo[bgcolor]?>" text="#<?=$userinfo[textcolor]?>" 
		link="#<?=$userinfo[textcolor]?>" vlink="#<?=$userinfo[textcolor]?>">
<div align='right' class='text'>
<a href='#' onClick="window.open('../lib/reportbug.php','bug_window','width=500,height=300')">
		send bug report</a>
</div>
<h2 class='black'>Confirm your playlist</h2>
<hr noshade size='1' width='40%' align='left'>
<?php
/* print out the show's info */
(! empty($playlistinfo->title)) ? print "<h2>$playlistinfo->title</h2><h3>$playlistinfo->subtitle</h3>\n" : 
		print "<h2>$playlistinfo->genre</h2>";
print "<h3> with $playlistinfo->djname</h3>\n";
print "<span class='text'><u>other shows</u> [link]</span><p>\n";
$end = $playlistinfo->starttime + $playlistinfo->duration*60*60;
print "<span class='text'>";
print date('l, F j, Y', $playlistinfo->starttime)."<br>\n";
print date('H:i', $playlistinfo->starttime)." to ".date('H:i', $end);
(! empty($playlistinfo->genre)) ? print "<br>$playlistinfo->othergenre<br>\n":''; 
print "</span>";

// print out an email link
($userinfo[emailpublish])? print "<span class='text'>
	<u>$userinfo[email]</u> [link]<br></span>": 
	print '';
(! empty($userinfo[link])) ? print "<span class='text'>
	<u>$userinfo[link]</u> [link]</text>":
	print '';
print "<p>";

if ( $playlistinfo->genre != "Classical")
	$headers = array( "artist"=>"Artist", "song"=>"Song", "album"=>"Album", 
					"label"=>"Label", "comments"=>"Comments", 
					"emph"=>"New", "request"=>"Request", "comp"=>"Comp");
else $headers = array("artist"=>"Composer", "song"=>"Piece", 
				"ensemble"=>"Ensemble/<br>Orchestra", "conductor"=>"Conductor", 
				"performer"=>"Soloist/<br>Performer", "label"=>"Label", 
				"comments"=>"Comments", "emph"=>"Recently<br>Released");
				
/* now iterate through the playlist outputting the songs in table format */
$cols = $playlist->cbits;
$colors = array("bgcolor"=>"$userinfo[bgcolor]", "tablecolor"=>"$userinfo[tablecolor]", "tabletext"=>"$userinfo[tabletext]", "tablehead"=>"$userinfo[tablehead]");

print "<table cellpadding='3' width='*'>\n\t<tr>\n";

foreach ($headers as $key=>$header)	{
	if ( isset( $cols[$key] ))
		print "\t\t<th bgcolor=\"#$colors[tablehead]\"> <font color='#$colors[tabletext]'>$header</font></th>\n";
}

print "\t</tr>\n";

$playlist->reset();
while ($playlist->hasNext())	{
	$row = $playlist->next();
	// special instructions for set breaks
	if ($row->artist == '*****' && $row->album == '*****' )    {
		if (empty($row->comments) )
			print "\t\t<tr height='0' cellpadding='1'><td style='line-height: 0' bgcolor='#$colors[bgcolor]' colspan='8'></td></tr>\n";
		else print "\t\t<tr cellpadding='1'><td colspan='8'><table width='100%'><tr><td class='mid' bgcolor='#$colors[bgcolor]' width='50%'><br><b>$row->comments</b></td><td></td></tr></table></td></tr>\n";
		continue;
	}

	// encode cell values for insound.com links
	$insound_artist = urlencode($row->artist);
	$insound_album = urlencode($row->album);
	$insound_label = urlencode($row->label);
	// print a row of the table
	print "\t<tr>\n";
	if ( $cols[artist] )
	print "\t\t<td class='mid' bgcolor=\"#$colors[tablecolor]\">$row->artist</td>\n";
	if ( $cols[song] )
	print "\t\t<td class='mid' bgcolor=\"#$colors[tablecolor]\"><font color='#$colors[tabletext]'>$row->song</font></td>\n";
	if ( $cols[album] )
	print "\t\t<td class='mid' bgcolor=\"#$colors[tablecolor]\">$row->album</td>\n";
	if ($cols[ensemble])
		print "\t\t<td class='mid' bgcolor=\"#$colors[tablecolor]\"><font color='#$colors[tabletext]'>$row->ensemble</font></td>\n";
	if ($cols[conductor])
		print "\t\t<td class='mid' bgcolor=\"#$colors[tablecolor]\"><font color='#$colors[tabletext]'>$row->conductor</font></td>\n";
	if ($cols[performer])
		print "\t\t<td class='mid' bgcolor=\"#$colors[tablecolor]\"><font color='#$colors[tabletext]'>$row->performer</font></td>\n";
	if ( $cols[label] )
	print "\t\t<td class='mid' bgcolor=\"#$colors[tablecolor]\">$row->label</td>\n";
	if ( $cols[comments] )
	print "\t\t<td class='mid' bgcolor=\"#$colors[tablecolor]\"><font color='#$colors[tabletext]'>$row->comments</font></td>\n";
	if ( $cols[emph] )
	print "\t\t<td class='mid' bgcolor=\"#$colors[tablecolor]\"><font color='#$colors[tabletext]'>";
		print (($row->emph == "NE" || $row->emph == "N") ? "*" : "");
		print "</font></td>\n";
	if ( $cols[request] )
	print "\t\t<td class='mid' bgcolor=\"#$colors[tablecolor]\"><font color='#$colors[tabletext]'>";
		print (($row->request) ? "R" : "");
		print "</font></td>\n";
	if ( $cols[comp] )
	print "\t\t<td class='mid' bgcolor=\"#$colors[tablecolor]\"><font color='#$colors[tabletext]'>";
		print (($row->comp) ? "C" : "");
		print "</font></td>\n";
	print "\t</tr>\n";
}
?>
</table>

<p>
<FORM method="POST">
<input type="hidden" name="show_id" value="<?= $show_id ?>">
<input type="hidden" name="referer" value="<?=$HTTP_REFERER ?>">
<table cellspacing="15">
	<tr>
		<td width="80">
		 <input type="submit" value="Confirm" name="form[confirm]"></td>
		<td>
		 <input type="submit" value="Go Back" name="form[reject]"></td>
	</tr>
</table>
</FORM>


</body>
</html>
