<?php
// $Id: newoldplaylist.php,v 1.5 2004/10/16 16:08:30 admin Exp $
/******************************************************************************
 * Theis Playlist Manager -- An interactive web application for creating,     *
 * editing, and publishing radio playlists.                                   *
 *                                                                            *
 * Copyright (C) 2003  Aaron Forrest                                          *
 *                                                                            *
 * This program is free software; you can redistribute it and/or              *
 * modify it under the terms of the GNU General Public License                *
 * as published by the Free Software Foundation; either version 2             *
 * of the License, or (at your option) any later version.                     *
 *                                                                            *
 * This program is distributed in the hope that it will be useful,            *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of             *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              *
 * GNU General Public License for more details.                               *
 *                                                                            *
 * You should have received a copy of the GNU General Public License          *
 * along with this program; if not, write to the Free Software                *
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.*
 *****************************************************************************/

// this is a pared down version of newplaylist.php

include("../lib/config.inc.php");
include("../lib/dblib.inc.php");
include("../lib/usrlib.inc.php");

checkUser();
checkGuestUser();

if (isset($_POST[action]) && $_POST[action] == "start" )
	{
	$message = "";
	if (empty ($_POST[form][djname]))
		$message .= "You must enter a DJ Name<br>";
	if ( ! checkdate($_POST[form][month], $_POST[form][day], $_POST[form][year]) )
		$message .= "You must enter a valid date<br>";
	if ($_POST[form][duration] == 0)
		$message .= "Show duration must be longer than 0<br>";
	if ($message == "")		// all tests are passed
		{
		$starttime = mktime($_POST[form][hour], $_POST[form][minute], 0, 
					$_POST[form][month], $_POST[form][day], $_POST[form][year]);
		$usersID = fetchUserID();
		$show_id = newShow($usersID, $starttime, $_POST[form][duration], 
				$_POST[form][djname], $_POST[form][title], 
				$_POST[form][subtitle], $_POST[form][genre], 
				$_POST[othergenre]);
		header("Location: editplaylist.php?show_id=$show_id");
	}
}


?>
<html>
<!-- This page generated by Theis Playlist Manager -->
<head>
<title>New Playlist</title>
<link href="../css/wprb.css" rel="stylesheet" type="text/css">
</head>
<body>
<div>
<?php
include( "usernav.inc" );
?>
</div>
<?php

if ($message != "" )	{
		print "<b>$message</b><br>\n";
}
	
print "<h2>Enter Show Details</h2>\n";
setShowDetails();

?>
</body>
</html>
