<?php
// $Id: newplaylist.php,v 1.7 2004/10/23 19:50:04 admin Exp $
/******************************************************************************
 * Theis Playlist Manager -- An interactive web application for creating,     *
 * editing, and publishing radio playlists.                                   *
 *                                                                            *
 * Copyright (C) 2003  Aaron Forrest                                          *
 *                                                                            *
 * This program is free software; you can redistribute it and/or              *
 * modify it under the terms of the GNU General Public License                *
 * as published by the Free Software Foundation; either version 2             *
 * of the License, or (at your option) any later version.                     *
 *                                                                            *
 * This program is distributed in the hope that it will be useful,            *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of             *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              *
 * GNU General Public License for more details.                               *
 *                                                                            *
 * You should have received a copy of the GNU General Public License          *
 * along with this program; if not, write to the Free Software                *
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.*
 *****************************************************************************/

include("../lib/config.inc.php");
include("../lib/dblib.inc.php");
include("../lib/usrlib.inc.php");
include("../lib/PlaylistSession.php");

checkUser();
if ( checkGuestUser() && $action != "start" )	{
	$action = "choose";
	$yesno = "no";
}

function chooseShow()
	{
	print "<div><table border=\"0\" width=\"100%\" height=\"100%\">\n";
	print "\t<tr>\n";
	print "\t\t<td width=\"30%\">&nbsp;</td>\n";
	print "\t\t<td>&nbsp;</td>\n";
	print "\t\t<td width=\"*\">&nbsp;</td>\n";
	print "\t</tr><tr height='100%'>\n";
	print "\t\t<td height='100%'>&nbsp;</td>\n";
	print "\t\t<td class='mid'><form method=\"POST\" action=\"newplaylist.php\">
				<input type=\"hidden\" name=\"action\" value=\"choose\">
				<b class='black'>Is this your regularly scheduled show?</b><br>
				<input type=\"radio\" name=\"yesno\" value=\"yes\">Yes<br>
				<input type=\"radio\" name=\"yesno\" value=\"no\">No
				<p><input type=\"submit\" value=\"Go\"></form></p></td>\n";
	print "\t\t<td>&nbsp;</td>\n";
	print "\t</tr></table></div>\n";
	}

if (isset($action) && $action == "choose")	{
	if ($yesno == "yes")	{
		$message = "";
		$usersrow = getRow("users", "loginsID", "$session[id]");
		if ( $usersrow[defday]=="" || $usersrow[defhour]==""
			|| $usersrow[defmin]=="" ||
			$usersrow[defduration]=="" ||
			$usersrow[defgenre]=="" )	{
			$message .= "Your defaults are not properly set. Please check your <a href='userprefs.php'>preferences</a><br>\n";
		}
		$sess_active = new PlaylistSession($link);
		if ($sess_active->active_show)
			$message .= "Sorry, you may not create a playlist while someone else is working on one";
		
		$show_id = defaultShow ($session[id]);
		if ($show_id === false)
			$message .= "Your defaults are not properly set. Please check your <a href='userprefs.php'>preferences</a><br>\n";

		if ($message == "")	{
			$userID = fetchUserID();
			$pl_session = new PlaylistSession($show_id, $userID, $link);
			header("Location: currplaylistframes.php?show_id=$show_id");
		}
	}
	elseif ($yesno == "no")	{
		include( "usernav.inc" );
		print "<h2>Enter Show Details</h2>\n";
		setShowDetails();
	}
}
		
if (isset($action) && $action == "start" )
	{
	$message = "";
	if (empty ($_POST[form][djname]))
		$message .= "You must enter a DJ Name<br>";
	if ( ! checkdate($form[month], $form[day], $form[year]) )
		$message .= "You must enter a valid date<br>";
	if ($form[duration] == 0)
		$message .= "Show duration must be longer than 0<br>";
	// check for other active sessions
	$sess_active = new PlaylistSession($link);
	if ($sess_active->active_show)
		$message .= "Sorry, you may not create a playlist while someone else is working on one";
	if ($message == "")		// all tests are passed
		{
		$starttime = mktime($form[hour], $form[minute], 0, 
					$form[month], $form[day], $form[year]);
		$usersID = fetchUserID();
		$show_id = newShow($usersID, $starttime, $_POST[form][duration], $form[djname],
				$form[title], $form[subtitle], $form[genre],
				$_POST[othergenre]);
		$pl_session = new PlaylistSession($show_id, $usersID, $link);
		header("Location: currplaylistframes.php?show_id=$show_id");
	}
}


?>
<html>
<!-- This page generated by Theis Playlist Manager -->
<head>
<title>New Playlist</title>
<link href="../css/wprb.css" rel="stylesheet" type="text/css">
</head>
<body>
<div>
<?php
if ($yesno != "no")
	include( "usernav.inc" );
?>
</div>
<?php


// if user tries to perform default show but no defaults are set,
// error message is printed and chooseShow form is printed again.
if ($message != "" )
	{
	$message = stripslashes($message);
	print "<b>$message</b>\n";
	if ($action == "start")	{
		print "<h2>Enter Show Details</h2>\n";
		setShowDetails();
	}
	elseif ($action == "choose")
		chooseShow();
	}
	if (isset($show_id) && ! empty($text))	{
		print $text;
	}
		
// if the form hasn't been submitted, the chooseShow form is printed.
if (! isset($action))
	{
	chooseShow();
	}


?>
</body>
</html>
