<?php
// $Id: oldplaylists.php,v 1.4 2004/01/09 03:27:50 admin Exp $
/******************************************************************************
 * Theis Playlist Manager -- An interactive web application for creating,     *
 * editing, and publishing radio playlists.                                   *
 *                                                                            *
 * Copyright (C) 2003  Aaron Forrest                                          *
 *                                                                            *
 * This program is free software; you can redistribute it and/or              *
 * modify it under the terms of the GNU General Public License                *
 * as published by the Free Software Foundation; either version 2             *
 * of the License, or (at your option) any later version.                     *
 *                                                                            *
 * This program is distributed in the hope that it will be useful,            *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of             *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              *
 * GNU General Public License for more details.                               *
 *                                                                            *
 * You should have received a copy of the GNU General Public License          *
 * along with this program; if not, write to the Free Software                *
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.*
 *****************************************************************************/

include("../lib/config.inc.php");
include("../lib/dblib.inc.php");
include("../lib/usrlib.inc.php");

checkUser();
$guest = checkGuestUser();

?>
<html>
<!-- This page generated by Theis Playlist Manager -->
<head>
<title>Your old playlists</title>
<link href="../css/wprb.css" rel="stylesheet" type="text/css">
</head>
<?php
include("usernav.inc")
?>
<body>
<h2>Choose a playlist to edit</h2>
<?php

writeListOfPlaylists( fetchUserID() );

print "<p>&nbsp;</p><p>&nbsp;</p>";

if ($guest)	{
	print "<table height='100%' width='600'>
		<tr valign='bottom'>
		<td class='text' width='500'>NOTE: If you are logged in as guest, you will 
		not be able to
		delete your playlists.  If you need to delete one, please
		contact an administrator with the date and time of the 
		playlist, and they will assist you</td>\n
		</tr></table>\n";
}

?>
</body>
</html>
