<?php
// $Id: previewcolors.php,v 1.4 2004/01/09 03:27:50 admin Exp $
/*****************************************************************************
* Theis Playlist Manager -- An interactive web application for creating,     *
* editing, and publishing radio playlists.                                   *
*                                                                            *
* Copyright (C) 2003  Aaron Forrest                                          *
*                                                                            *
* This program is free software; you can redistribute it and/or              *
* modify it under the terms of the GNU General Public License                *
* as published by the Free Software Foundation; either version 2             *
* of the License, or (at your option) any later version.                     *
*                                                                            *
* This program is distributed in the hope that it will be useful,            *
* but WITHOUT ANY WARRANTY; without even the implied warranty of             *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              *
* GNU General Public License for more details.                               *
*                                                                            *
* You should have received a copy of the GNU General Public License          *
* along with this program; if not, write to the Free Software                *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.*
*****************************************************************************/

include("../lib/config.inc.php");
include("../lib/dblib.inc.php");
include("../lib/usrlib.inc.php");

checkUser();
if ( checkGuestUser() )	{
	header( "Location: usermenu.php" );
	exit;
}
?>
<html>
<!-- This page generated by Theis Playlist Manager -->
<head>
<title>color preferences preview</title>
</head>
<body bgcolor="#<?=$_GET[bgcolor]?>" text="#<?=$_GET[textcolor]?>">
<h2>Testing your colors...</h2>
<table width="100%" cellspacing="2" style="color: #<?=$_GET[tabletext]?>">
	<tr>
		<th bgcolor="#<?=$_GET[tablehead]?>">Artist</th>
		<th bgcolor="#<?=$_GET[tablehead]?>">Song</th>
		<th bgcolor="#<?=$_GET[tablehead]?>">Album</th>
	</tr><tr>
		<td bgcolor="#<?=$_GET[tablecolor]?>">an artist</td>
		<td bgcolor="#<?=$_GET[tablecolor]?>">a song</td>
		<td bgcolor="#<?=$_GET[tablecolor]?>">an album</td>
	</tr><tr>
		<td bgcolor="#<?=$_GET[tablecolor]?>">an artist</td>
		<td bgcolor="#<?=$_GET[tablecolor]?>">a song</td>
		<td bgcolor="#<?=$_GET[tablecolor]?>">an album</td>
	</tr><tr>
		<td bgcolor="#<?=$_GET[tablecolor]?>">an artist</td>
		<td bgcolor="#<?=$_GET[tablecolor]?>">a song</td>
		<td bgcolor="#<?=$_GET[tablecolor]?>">an album</td>
	</tr><tr>
		<td bgcolor="#<?=$_GET[tablecolor]?>">an artist</td>
		<td bgcolor="#<?=$_GET[tablecolor]?>">a song</td>
		<td bgcolor="#<?=$_GET[tablecolor]?>">an album</td>
	</tr><tr>
		<td bgcolor="#<?=$_GET[tablecolor]?>">an artist</td>
		<td bgcolor="#<?=$_GET[tablecolor]?>">a song</td>
		<td bgcolor="#<?=$_GET[tablecolor]?>">an album</td>
	</tr>
</table>


</body>
</html>
