<?php
// $Id: userprefs.php,v 1.4 2004/01/09 03:27:50 admin Exp $
/******************************************************************************
 * Theis Playlist Manager -- An interactive web application for creating,     *
 * editing, and publishing radio playlists.                                   *
 *                                                                            *
 * Copyright (C) 2003  Aaron Forrest                                          *
 *                                                                            *
 * This program is free software; you can redistribute it and/or              *
 * modify it under the terms of the GNU General Public License                *
 * as published by the Free Software Foundation; either version 2             *
 * of the License, or (at your option) any later version.                     *
 *                                                                            *
 * This program is distributed in the hope that it will be useful,            *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of             *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              *
 * GNU General Public License for more details.                               *
 *                                                                            *
 * You should have received a copy of the GNU General Public License          *
 * along with this program; if not, write to the Free Software                *
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.*
 *****************************************************************************/

include("../lib/config.inc.php");
include("../lib/dblib.inc.php");
include("../lib/usrlib.inc.php");

checkUser();
if ( checkGuestUser() )	{
	header("Location: usermenu.php");
}

// check if form is filled out OK [DJ has not selected black on black
// as color scheme, etc] and send updated preferences to database.
// If there is a problem with the submission, the user is redirected
// to this page to try again.
if ( isset($action) && $action == "edit" )
	{
	$message = "";
	if ($form_bgcolor == $form_textcolor || $form_tablecolor == $form_tabletext || $form_tablehead == $form_tabletext)
		$message .= "You cannot set text and background to the same color<br>\n";
	if (empty($form[email]))
		$message .= "You must enter an email address<br>\n";
	if (! empty($form[email]) && preg_match("/\A\w+(\.\w+)*@(\w+\.)+\w+\Z/", $form[email], $array) == false )
		$message .= "You must enter a valid email address<br>\n";
	if (! empty($form[link]) && ! is_url($form[link])) // weak url validation
		$message .= "Your url must be in the correct format (http://www.example.com/...)";
	if (! empty($form[showdesc]) && strlen($form[showdesc]) > 1000)
		$message .= "Show description length must be less than 1000 characters";
	if ( $form[password] != $form[password2])
		$message .= "Your passwords did not match";
	if ($message == "" ) // entry passes muster
		{
		updateUserPrefs($form[email], $form[emailpublish], $form[link], $form[offsite],
					$form_bgcolor, $form_tablehead, $form_tablecolor, $form_textcolor, $form_tabletext,
					$form[weekday], $form[hour], $form[minute],
					$form[duration], $form[genre], $form[othergenre],
					$form[djname], $form[title], $form[subtitle], addslashes($form[showdesc]), $form[djID], $form[password]);
		header( "Location: usermenu.php");
		}
	}


?>

<html>
<!-- This page generated by Theis Playlist Manager -->
<head>
<title>Edit User preferences</title>
<link href="../css/wprb.css" rel="stylesheet" type="text/css">
</head>
<body>
<?php
include("usernav.inc");
// print error messages, if such exist
if ($message != "")
	print "<b>$message</b><br>\n";
	
// get dj preferences from database
$dj_prefs = getRow("users", "loginsID", $session[id], 'i');
?>

<h2>Edit user preferences for <?= $dj_prefs[firstname]." ".$dj_prefs[lastname] ?></h2>

<!-- start of preferences form -->
<form action="<?= $PHP_SELF?>" method="POST" name="the_form">
<!-- hidden fields keep shit[flow] in order -->
<input type="hidden" name="action" value="edit">
<input type="hidden" name="form[djID]" value="<?= $dj_prefs[loginsID] ?>">

<p>
<b class='black'>Email address:</b> <br>
<input type="text" name="form[email]" value="<?= $dj_prefs[email] ?>">
<br>
<span class='text'>Publish email?</span>
	<input type="checkbox" name="form[emailpublish]" value="1"
	<?php
		if ( $dj_prefs[emailpublish] )
			print "CHECKED";
	?>> <span class='text'>(check box if you want your email published)</span>
</p>
<p>
<b class='black'>Change password:</b><br>
<span class='text'>Enter new password: </span>
	<input type="password" name="form[password]" value="" maxlength="20"><br>
<span class='text'>Confirm password: </span>
	<input type="password" name="form[password2]" value="" maxlength="20">
</p>
<p>
<b class='black'>Your show's homepage:</b><br>
<input type="text" size='50' name="form[link]" value="<?= $dj_prefs[link] ?>">
<br>
<span class="text">Redirect to this site? </span>
	<input name="form[offsite]" type="checkbox" value="1"
		<?= (($dj_prefs[offsite]) ? "CHECKED" : ""); ?>
		><span class="text">(check if you want your show's link on the schedule to go to the page specified above)</span>
</p>

<p>
<b class='black'>Color scheme:</b><br>
<table border="0">
 <tr>
	<td class='mid'>Background</td>
	<td class='mid'>Table header</td>
	<td class='mid'>Table cells</td>
	<td class='mid'>Text</td>
	<td class='mid'>Table text</td>
 </tr>
 <tr>
	<!-- the options for these selectors are written by functions in djlib.inc
		 onChange element changes text input below to match selector value when selected.
		 this lets djs either select from the list or input their own color values in hex. -->
	<td width="100">
		<select name="sel_bgcolor" onChange="document.the_form.form_bgcolor.value=document.the_form.sel_bgcolor.options[selectedIndex].value">
		 	<?php writeColorOptions($dj_prefs[bgcolor]); ?>
		</select></td>
	<td width="100">
		<select name="sel_tablehead" onChange="document.the_form.form_tablehead.value=document.the_form.sel_bgcolor.options[selectedIndex].value">
			<?php writeColorOptions($dj_prefs[tablehead]); ?>
		</select></td>
	<td width="100">
		<select name="sel_tablecolor" onChange="document.the_form.form_tablecolor.value=document.the_form.sel_tablecolor.options[selectedIndex].value">
 			<?php writeColorOptions($dj_prefs[tablecolor]); ?>
		</select></td>
	<td width="100">
		<select name="sel_textcolor" onChange="document.the_form.form_textcolor.value=document.the_form.sel_textcolor.options[selectedIndex].value">
 			<?php writeColorOptions($dj_prefs[textcolor]); ?>
		</select></td>
	<td width="100">
		<select name="sel_tabletext" onChange="document.the_form.form_tabletext.value=document.the_form.sel_tabletext.options[selectedIndex].value">
			<?php writeColorOptions($dj_prefs[tabletext]); ?>
		</select></td>
	<!-- preview link opens a popup with a table configured to those values set by user -->
	<td><a href="#" onClick="var bgcolor=document.the_form.form_bgcolor.value; var tablecolor=document.the_form.form_tablecolor.value;
										var textcolor=document.the_form.form_textcolor.value;
										var tabletext=document.the_form.form_tabletext.value;
										var tablehead=document.the_form.form_tablehead.value;
										var preview_url = 'previewcolors.php?bgcolor=' + bgcolor + '&tablecolor=' + tablecolor + '&textcolor=' + 
															textcolor + '&tabletext=' + tabletext + '&tablehead=' + tablehead;
										prevWin = window.open(preview_url, 'preview_window', 'width=500,height=400,status=no,resizeable'); 
										prevWin.focus()">preview</a></td>
 </tr><tr>
 	<td>#<input type="text" size="6" name="form_bgcolor" value="<?=$dj_prefs[bgcolor]?>"</td>
	<td>#<input type="text" size="6" name="form_tablehead" value="<?=$dj_prefs[tablehead]?>"</td>
	<td>#<input type="text" size="6" name="form_tablecolor" value="<?=$dj_prefs[tablecolor]?>"</td>
	<td>#<input type="text" size="6" name="form_textcolor" value="<?=$dj_prefs[textcolor]?>"</td>
	<td>#<input type="text" size="6" name="form_tabletext" value="<?=$dj_prefs[tabletext]?>"</td>
	<td>&nbsp;</td>
 </tr>
</table>
</p>

<p>
<b class='black'>Default showtime:</b><br>
<table border="0" >
 <tr>
	<td class='mid' width="110">Day:</td>
	<td class='mid' width="110">Start time:</td>
	<td class='mid'>Duration:</td>
 </tr>
 <tr>
	<td>
		<select name="form[weekday]">
			<?php writeWeekdayOptions($dj_prefs[defday]); ?>
		</select>
	</td><td>
		<select name="form[hour]">
			<?php writeHourOptions($dj_prefs[defhour]); ?>
		</select>
		<select name="form[minute]">
			<?php writeMinuteOptions($dj_prefs[defmin]); ?>
		</select>
	</td><td>
		<select name="form[duration]">
			<?php writeDurationOptions($dj_prefs[defduration]); ?>
		</select>
	</td>
 </tr>
</table>
</p>

<p>
<b class='black'>Default genre: [for tracking purposes]</b><br>
<select name="form[genre]">
	<?php writeGenreOptions(); ?>
</select>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<span class='text'>specialty/subgenre: </span>
<input type="text" name="form[othergenre]" value="<?= $dj_prefs[defothergenre] ?>">
</p>

<p>
<b class='black'>DJ name:</b> <br>
<input type="text" name="form[djname]" value="<?= $dj_prefs[defdjname] ?>">
</p>

<p>
<b class='black'>Show title:</b> <br>
<input type="text" name="form[title]" value="<?= $dj_prefs[deftitle] ?>">
</p>

<p>
<b class='black'>Show subtitle:</b> <br>
<input type="text" name="form[subtitle]" value="<?= $dj_prefs[defsubtitle] ?>">
</p>

<p>
<b class="black"> Show description:</b> <br>
<textarea cols="35" rows="7" name="form[showdesc]">
<?= stripslashes($dj_prefs[defdesc]) ?>
</textarea>
</p>

<p>
<input type="submit" value="Submit changes">

</form>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<span class='text'>
	<a href="usermenu.php">Cancel changes</a>
</span>
</body>
</html>
