<?php
// $Id: usermenu.php,v 1.9 2004/01/09 03:27:50 admin Exp $
/******************************************************************************
 * Theis Playlist Manager -- An interactive web application for creating,     *
 * editing, and publishing radio playlists.                                   *
 *                                                                            *
 * Copyright (C) 2003  Aaron Forrest                                          *
 *                                                                            *
 * This program is free software; you can redistribute it and/or              *
 * modify it under the terms of the GNU General Public License                *
 * as published by the Free Software Foundation; either version 2             *
 * of the License, or (at your option) any later version.                     *
 *                                                                            *
 * This program is distributed in the hope that it will be useful,            *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of             *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              *
 * GNU General Public License for more details.                               *
 *                                                                            *
 * You should have received a copy of the GNU General Public License          *
 * along with this program; if not, write to the Free Software                *
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.*
 *****************************************************************************/

include("../lib/config.inc.php");
include("../lib/dblib.inc.php");
include("../lib/usrlib.inc.php");

checkUser();
$guest = checkGuestUser();
?>
<html>
<!-- This page generated by Theis Playlist Manager -->
<head>
<title>DJ Main Menu</title>
<link href="../css/wprb.css" rel="stylesheet" type="text/css">
</head>
<body>
<?php
include("usernav.inc");
?>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>You are logged in as </b><b class="black"><?=$session[login]?></b>

<h2>&nbsp;&nbsp;
Select a task</h2>
<dl>
	<dt><span class='text'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="newplaylist.php">Start a new playlist</a> &nbsp;(use only if you are on the air now)</span>
	<dt><span class="text">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="newoldplaylist.php">Enter an old playlist</a></span>
	<dt><span class='text'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="oldplaylists.php">Edit a playlist</a></span><p>
<?php
if ( ! $guest )	{
?>
	<dt><span class='text'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="userprefs.php">Edit preferences</a></span><p>
<?php	}	?>
	<dt><span class='text'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="../lib/logout.php">Logout</a></span>
</dl>
</body>
</html>
