<?php
// $Id: currentplaylist.php,v 1.14 2004/09/27 22:18:00 admin Exp $
 /*****************************************************************************
 * Theis Playlist Manager -- An interactive web application for creating,     *
 * editing, and publishing radio playlists.                                   *
 *                                                                            *
 * Copyright (C) 2003  Aaron Forrest                                          *
 *                                                                            *
 * This program is free software; you can redistribute it and/or              *
 * modify it under the terms of the GNU General Public License                *
 * as published by the Free Software Foundation; either version 2             *
 * of the License, or (at your option) any later version.                     *
 *                                                                            *
 * This program is distributed in the hope that it will be useful,            *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of             *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              *
 * GNU General Public License for more details.                               *
 *                                                                            *
 * You should have received a copy of the GNU General Public License          *
 * along with this program; if not, write to the Free Software                *
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.*
 *****************************************************************************/

/* always include this first */
include("config.inc.php");

/* we are going to use the playlist class */
import("org/wprb/Playlist.php");
import("org/wprb/user.php");
import("org/wprb/ObjectCache.php");
define("__OBJECTCACHE_DIR__", "./cache");
define("__OBJECTCACHE_TIMEOUT__", (30));

// instantiate caching object
$debug = $_GET["debug"];

$pcache = new ObjectCache("currentplaylist.cache", 30);
if ($debug) print "<pre>cache:new -- $pcache->error </pre><br />";

// load from cache, se possibile
$nowarray = $pcache->load(null);
if ($debug) print "<pre>cache:load -- $pcache->error </pre><br />";

// extract $nowplaylist and $user to current symbol table
if ( is_array($nowarray) )	extract($nowarray, EXTR_OVERWRITE);

// cache nonexistent or too old -- refresh from DB
if ( ! $nowplaylist )	{
	$nowplaylist = "empty";
	
	/* now lets create an instance of the class (get playlist with id=5) *
	 * then get basic information about that playlist 					 */
	$playlist = new Playlist();
	
	if ( $playlist->id)	{	// current playlist exists
		$nowplaylist = $playlist;
		
		// get details about the current playlist
		$nowplaylist->getPlaylistInfo();
		$playlistinfo = $nowplaylist->info;
		
		/* get user info for this playlist */
		$user = new User($playlistinfo->userID);
		
		// store new playlist and user information in cache
		$pcache->store( array( "nowplaylist"=>$nowplaylist, "user"=>$user ));
		if ($debug) print "<pre>cache:store -- $pcache->error </pre><br />";
	}
	else	header("Location: offair.php"); // redirect to the no playlist page
}

else	{
	// get details about the current playlist
	$playlistinfo = $nowplaylist->info;
}

$userinfo = $user->returnUserInfo();

?>

<html>
<!-- This page generated by Theis Playlist Manager -->
<head>
<title>::ON THE AIR:: <?= $playlistinfo->title ?></title>

<style type="text/css">
@import url(wprb.css);
h2	{ color:#<?=$userinfo[textcolor]?> }
h3 { color: #<?=$userinfo[textcolor]?>; line-height:.5 }
.text { color: #<?=$userinfo[textcolor]?> }
a { color: #<?=$userinfo[textcolor]?> }
b { color: #<?=$userinfo[textcolor]?> }
.black { color: #<?=$userinfo[textcolor]?> }
</style>

<meta http-equiv='REFRESH' content='60'>
<script language="JavaScript" src="jscripts.js"></script>
</head>

<body bgcolor="<?=$userinfo[bgcolor]?>" text="<?=$userinfo[textcolor]?>" 
		link="<?=$userinfo[textcolor]?>" vlink="<?=$userinfo[textcolor]?>">

<!-- ************ REMOVABLE ************ -->
<?php
// import the toolbar
print "<div class='text'>\n";
include("worldnav.html");
print "</div><p>\n";
?>
<span class='text'><b>Listen:</b> <a href='<?=__REAL__?>'>real</a> |
		<a href='<?= __WMP56__?>'>wmp56</a> |
		<a href='<?= __WMP100__?>'>wmp100</a> ||
<b>Request:</b> <a href='mailto:requests@wprb.com'>email dj</a></span>
<h2><?= __STATION__ ?> ON-AIR PLAYLIST</h2>

<!-- ********** END REMOVABLE ********** -->
<?php

/* print out the show's info */
print ((! empty($playlistinfo->title)) ? "<h2>$playlistinfo->title</h2>\n" : 
		"<h2>$playlistinfo->othergenre</h2>" );
print ((! empty($playlistinfo->subtitle)) ? "<b class='black'>$playlistinfo->subtitle</b><br>\n":"");
print "<h3> with $playlistinfo->djname</h3>\n";
print "<span class='text'><a href=\"djplaylists.php?id=$playlistinfo->userID\">other shows</a></span><p>\n";
$end= $playlistinfo->starttime + $playlistinfo->duration*60*60;
print "<span class='text'>";
print date('l, F j, Y', $playlistinfo->starttime)."<br>\n";
print date('H:i', $playlistinfo->starttime)." to ".date('H:i', $end);
(! empty($playlistinfo->genre)) ? print "<br>$playlistinfo->othergenre<br>\n":''; 
print "</span>";

// print out an email link
($userinfo[emailpublish])? print "<span class='text'>
	<a href='mailto:$userinfo[email]'>$userinfo[email]</a><br></span>": 
	print '';
(! empty($userinfo[link])) ? print "<span class='text'>
	<a href='$userinfo[link]'>$userinfo[link]</a></text>":
	print '';
print "<p>";

if ( $playlistinfo->genre != "Classical")
	$headers = array( "artist"=>"Artist", "song"=>"Song", "album"=>"Album", 
					"label"=>"Label", "comments"=>"Comments", 
					"emph"=>"New", "request"=>"Request", "comp"=>"Comp");
else $headers = array("artist"=>"Composer", "song"=>"Piece", 
				"ensemble"=>"Ensemble/<br>Orchestra", "conductor"=>"Conductor", 
				"performer"=>"Soloist/<br>Performer", "label"=>"Label", 
				"comments"=>"Comments", "emph"=>"Recently<br>Released");

/* now iterate through the playlist outputting the songs in table format */
$cols = $nowplaylist->cbits;
$colors = array("bgcolor"=>"$userinfo[bgcolor]", "tablecolor"=>"$userinfo[tablecolor]", "tabletext"=>"$userinfo[tabletext]", "tablehead"=>"$userinfo[tablehead]");

print "<table cellpadding='3' width='*'>\n\t<tr>\n";

foreach ($headers as $key=>$header)	{
	if ( isset( $cols[$key] ))
		print "\t\t<th bgcolor=\"#$colors[tablehead]\"> <font color='#$colors[tabletext]'>$header</font></th>\n";
}

print "\t</tr>\n";

$nowplaylist->reset();
while ($nowplaylist->hasNext())	{
	$row = $nowplaylist->next();
	// special instructions for set breaks
	if ($row->artist == '*****' && $row->album == '*****' )    {
		if (empty($row->comments) )
			print "\t\t<tr height='0' cellpadding='1'><td style='line-height: 0' bgcolor='#$colors[bgcolor]' colspan='8'></td></tr>\n";
		else print "\t\t<tr cellpadding='1'><td colspan='8'><table width='100%'><tr><td class='mid' bgcolor='#$colors[bgcolor]' width='50%'><br><b>$row->comments</b></td><td></td></tr></table></td></tr>\n";
		continue;
	}

	// encode cell values for insound.com links
	$insound_artist = urlencode($row->artist);
	$insound_album = urlencode($row->album);
	$insound_label = urlencode($row->label);
	// print a row of the table
	print "\t<tr>\n";
	if ( $cols[artist] )
	print "\t\t<td class='mid' bgcolor=\"#$colors[tablecolor]\"><a style='color:#$colors[tabletext]' href=\"\" onClick=\"handle_popup('".__ETAIL_ARTIST__."$insound_artist'); return false;\">$row->artist</a></td>\n";
	if ( $cols[song] )
	print "\t\t<td class='mid' bgcolor=\"#$colors[tablecolor]\"><font color='#$colors[tabletext]'>$row->song</font></td>\n";
	if ( $cols[album] )
	print "\t\t<td class='mid' bgcolor=\"#$colors[tablecolor]\"><a style='color:#$colors[tabletext]' href=\"\" onClick=\"handle_popup('".__ETAIL_ALBUM__."$insound_album'); return false;\">$row->album</a></td>\n";
	if ($cols[ensemble])
		print "\t\t<td class='mid' bgcolor=\"#$colors[tablecolor]\"><font color='#$colors[tabletext]'>$row->ensemble</font></td>\n";
	if ($cols[conductor])
		print "\t\t<td class='mid' bgcolor=\"#$colors[tablecolor]\"><font color='#$colors[tabletext]'>$row->conductor</font></td>\n";
	if ($cols[performer])
		print "\t\t<td class='mid' bgcolor=\"#$colors[tablecolor]\"><font color='#$colors[tabletext]'>$row->performer</font></td>\n";
	if ( $cols[label] )
	print "\t\t<td class='mid' bgcolor=\"#$colors[tablecolor]\"><a style='color:#$colors[tabletext]' href=\"\" onClick=\"handle_popup('".__ETAIL_LABEL__."$insound_label'); return false;\">$row->label</a></td>\n";
	if ( $cols[comments] )
	print "\t\t<td class='mid' bgcolor=\"#$colors[tablecolor]\"><font color='#$colors[tabletext]'>$row->comments</font></td>\n";
	if ( $cols[emph] )
	print "\t\t<td class='mid' bgcolor=\"#$colors[tablecolor]\"><font color='#$colors[tabletext]'>";
		print (($row->emph == "NE" || $row->emph == "N") ? "*" : "");
		print "</font></td>\n";
	if ( $cols[request] )
	print "\t\t<td class='mid' bgcolor=\"#$colors[tablecolor]\"><font color='#$colors[tabletext]'>";
		print (($row->request) ? "R" : "");
		print "</font></td>\n";
	if ( $cols[comp] )
	print "\t\t<td class='mid' bgcolor=\"#$colors[tablecolor]\"><font color='#$colors[tabletext]'>";
		print (($row->comp) ? "C" : "");
		print "</font></td>\n";
	print "\t</tr>\n";
}
?>
</table>
<p class='text'>
<a style='text-decoration: none' href="" onClick="handle_popup('<?=__ETAIL_LINK__?>'); return false;"><img src='insound.png' alt='support wprb::shop at insound.com' border='0'></a>
</p>
<p class='text'>
<?php
include("worldnav.html")
?>
</p>
</body>
</html>
