<?php
// $Id: djplaylists.php,v 1.6 2004/01/04 07:24:29 admin Exp $
/*****************************************************************************
* Theis Playlist Manager -- An interactive web application for creating,     *
* editing, and publishing radio playlists.                                   *
*                                                                            *
* Copyright (C) 2003  Aaron Forrest                                          *
*                                                                            *
* This program is free software; you can redistribute it and/or              *
* modify it under the terms of the GNU General Public License                *
* as published by the Free Software Foundation; either version 2             *
* of the License, or (at your option) any later version.                     *
*                                                                            *
* This program is distributed in the hope that it will be useful,            *
* but WITHOUT ANY WARRANTY; without even the implied warranty of             *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              *
* GNU General Public License for more details.                               *
*                                                                            *
* You should have received a copy of the GNU General Public License          *
* along with this program; if not, write to the Free Software                *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.*
*****************************************************************************/

// page on which selected dj's playlists are displayed


/* always include this first */
include("config.inc.php");

/* we are going to use the user class */
import("org/wprb/user.php");

// create the dj object and get its playlists
$dj = new User($_GET[id]);
$playlists = $dj->getPlaylists();

?>

<!-- This page generated by Theis Playlist Manager -->
<html>
<head>
<title>Playlists for <?= $dj->defdjname ?> </title>
<style type="text/css">
@import url(wprb.css);
h2	{ color:#<?=$dj->textcolor?> }
h3 { color: #<?=$dj->textcolor?> }
.text { color: #<?=$dj->textcolor?> }
a { color: #<?=$dj->textcolor?> }
b { color: #<?=$dj->textcolor?> }
</style>
</head>
<body bgcolor="#<?= $dj->bgcolor ?>" text="#<?= $dj->textcolor ?>" link="#<?= $dj->textcolor ?>" vlink="#<?= $dj->textcolor ?>">

<!-- ************ REMOVABLE ************ -->
<?php
// import the toolbar
include("worldnav.html");
print "<p>\n";
?>
<!-- ********** END REMOVABLE ********** -->

<h2>Playlists for <?= (! empty($dj->deftitle)) ? $dj->deftitle : $dj->defdjname ?></h2>
<?php
print (($dj->defsubtitle) ? "<b class='text'>$dj->defsubtitle</b><br>\n" : "" );
print ((! empty($dj->deftitle)) ? "<span class='text'>with <b>$dj->defdjname</b></span><br>\n" : "");
print "<span class='text'>$dj->defothergenre</span><br>\n";
print (($dj->defdesc) ? "<p class='text'>".stripslashes($dj->defdesc)."</p>\n" : "" );
print (($dj->link) ? "<span class='text'><a href='$dj->link'>$dj->link</a></span><br>" : "");
print (($dj->email && $dj->emailpublish) ? "<span class='text'><a href='mailto:$dj->email'>$dj->email</a></span><br>\n" : "");

print "<br><p class=\"text\">\n";
$playlists->reset();
while ($playlists->hasNext())
	{
	$row = $playlists->next();
	print "<a href=\"printplaylist.php?show_id=$row->ID\">";
	print date('l, F j, Y, H:i', $row->starttime);
	print "</a><br>\n";
	}
print "</p>\n";
?>



</body>
</html>
