<?php
// $Id: last10.php,v 1.5 2003/12/23 05:50:56 admin Exp $
/*****************************************************************************
* Theis Playlist Manager -- An interactive web application for creating,     *
* editing, and publishing radio playlists.                                   *
*                                                                            *
* Copyright (C) 2003  Aaron Forrest                                          *
*                                                                            *
* This program is free software; you can redistribute it and/or              *
* modify it under the terms of the GNU General Public License                *
* as published by the Free Software Foundation; either version 2             *
* of the License, or (at your option) any later version.                     *
*                                                                            *
* This program is distributed in the hope that it will be useful,            *
* but WITHOUT ANY WARRANTY; without even the implied warranty of             *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              *
* GNU General Public License for more details.                               *
*                                                                            *
* You should have received a copy of the GNU General Public License          *
* along with this program; if not, write to the Free Software                *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.*
*****************************************************************************/

// a list of the last ten days of shows

define("TENDAYS", (10*24*60*60)); // number of seconds in 10 days

/* always include this first */
include("config.inc.php");

/* we are going to use the ShowList class */
import("org/wprb/ShowList.php");
$today = time();
$start = $today - TENDAYS;
$s_list = new ShowList($start, $today);
$s_list->reset();

?>
<html>
<!-- This page generated by Theis Playlist Manager -->
<head>
 <title>Last 10 Days of shows</title>
 <link href="wprb.css" rel='styleSheet' type="text/css">
</head>
<body>

<!-- ************ REMOVABLE ************ -->
<?php 
include("worldnav.html");
?>
<p>&nbsp;
<h2>List of shows for the last 10 days</h2>
<!-- ********** END REMOVABLE ********** -->

<div class='text'>
<table cellpadding="5">
<?php
while ( $s_list->hasNext() )	{
	$row = $s_list->next();
	$day = getdate($row->starttime);
	// shade color depends on day of week
	($day[wday]%2) ? $bgcol="#F0F0F0" : $bgcol = "#EEEEFF";
	print "\t<tr>\n\t\t<td class='mid' width='60%' bgcolor='$bgcol'>";
	print "<a href=\"printplaylist.php?show_id=$row->ID\">";
	if (! empty($row->title) )
		print "$row->title";
	else print "$row->othergenre";
	print " with $row->djname</a></td>\n";
	print "\t\t<td class='mid' bgcolor='$bgcol'>".date("l, F j, Y, H:i", $row->starttime)." - ";
	print date("H:i", ($row->starttime+$row->duration*60*60))."</td>\n";
	print "\t</tr>\n";
}

?>
</div>
</body>
</html>
