<?php
// $Id: offair.php,v 1.5 2004/03/21 23:38:23 admin Exp $
 /*****************************************************************************
 * Theis Playlist Manager -- An interactive web application for creating,     *
 * editing, and publishing radio playlists.                                   *
 *                                                                            *
 * Copyright (C) 2003  Aaron Forrest                                          *
 *                                                                            *
 * This program is free software; you can redistribute it and/or              *
 * modify it under the terms of the GNU General Public License                *
 * as published by the Free Software Foundation; either version 2             *
 * of the License, or (at your option) any later version.                     *
 *                                                                            *
 * This program is distributed in the hope that it will be useful,            *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of             *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              *
 * GNU General Public License for more details.                               *
 *                                                                            *
 * You should have received a copy of the GNU General Public License          *
 * along with this program; if not, write to the Free Software                *
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.*
 *****************************************************************************/
include("config.inc.php");
?>
<html>
<head>
<!-- This page generated by Theis Playlist Manager -->
<title><?= __STATION__ ?> DJ is off line</title>
<style type="text/css">
@import url(wprb.css);
.text { color: #335 }
.grey { color: #666; font-size: 28px}
</style>
<meta http-equiv="refresh" content="300;currentplaylist.php">
</head>
<body bgcolor="#000033">
<!-- ************ REMOVABLE ************ -->
<div class="text">
<?php
include("worldnav.html");
?>
</div>
<!-- ********** END REMOVABLE ********** -->

<table width='100%' height='100%' border='0'>
	<tr>
		<td align='center' valign='middle' height="*">
		<h2 class='grey'><?= __STATION__ ?> DJ IS OFF LINE</h2>
		<span class='text'>Please try again later...</span>
		</td>
	</tr>
</table>
</body>
</html>
