<?php
// $Id: schedulelist.php,v 1.4 2003/12/23 05:50:56 admin Exp $
/*****************************************************************************
* Theis Playlist Manager -- An interactive web application for creating,     *
* editing, and publishing radio playlists.                                   *
*                                                                            *
* Copyright (C) 2003  Aaron Forrest                                          *
*                                                                            *
* This program is free software; you can redistribute it and/or              *
* modify it under the terms of the GNU General Public License                *
* as published by the Free Software Foundation; either version 2             *
* of the License, or (at your option) any later version.                     *
*                                                                            *
* This program is distributed in the hope that it will be useful,            *
* but WITHOUT ANY WARRANTY; without even the implied warranty of             *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              *
* GNU General Public License for more details.                               *
*                                                                            *
* You should have received a copy of the GNU General Public License          *
* along with this program; if not, write to the Free Software                *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.*
*****************************************************************************/
// a list of old schedules page

/* always include this first */
include("config.inc.php");

/* we are going to use the ScheduleList class */
import("org/wprb/ScheduleList.php");

$s_list = new ScheduleList();
$s_list->reset();

?>
<html>
<!-- This page generated by Theis Playlist Software -->
<head>
<title>WPRB Old Schedules</title>
<link href="wprb.css" rel='styleSheet' type="text/css">
</head>
<body>
<!-- ************ REMOVABLE ************ -->
<?php 
include("worldnav.html");
?>
<h2> Old Schedules </h2>
<!-- ********** END REMOVABLE ********** -->

<div class='text'>
<?php
$seasons = array("Fall", "Spring", "Summer");
while ( $s_list->hasNext() )	{
	$row = $s_list->next();
	foreach ( $seasons as $key=>$season )
		if ($row->season == $key)
			$row->season = $season;
	if (! $row->current)
		print "<a href='oldschedule.php?id=$row->ID'>$row->season $row->year</a>
				<br>\n";
}

?>
</div>
</body>
</html>
