<?php
// $Id: search.php,v 1.12 2004/09/27 22:18:00 admin Exp $
/*****************************************************************************
* Theis Playlist Manager -- An interactive web application for creating,     *
* editing, and publishing radio playlists.                                   *
*                                                                            *
* Copyright (C) 2003  Aaron Forrest                                          *
*                                                                            *
* This program is free software; you can redistribute it and/or              *
* modify it under the terms of the GNU General Public License                *
* as published by the Free Software Foundation; either version 2             *
* of the License, or (at your option) any later version.                     *
*                                                                            *
* This program is distributed in the hope that it will be useful,            *
* but WITHOUT ANY WARRANTY; without even the implied warranty of             *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              *
* GNU General Public License for more details.                               *
*                                                                            *
* You should have received a copy of the GNU General Public License          *
* along with this program; if not, write to the Free Software                *
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.*
*****************************************************************************/
include("config.inc.php");

import("org/wprb/Users.php");
import("org/wprb/Search.php");

include("options.inc.php");

function trimEnd($str, $tail)	{
	if( $tail_pos = strpos($str, $tail) )	{
		return substr($str, 0, ($tail_pos - 1));
	}
	else return $str;
}

if (! isset($_GET[form][startmon]) || ! isset($_GET[form][endmon]))	{
	$zerotime = getdate(0);
	$nowtime = getdate();
	$form[startmon] = 1;
	$form[startmday] = 1;
	$form[startyear] = 2003; // year database was implemented
	$form[endmon] = $nowtime[mon];
	$form[endmday] = $nowtime[mday];
	$form[endyear] = $nowtime[year];
	$form[endhour] = $nowtime[hours];
	$form[endmin] = $nowtime[minutes];
}

// send query to db after form has been submitted
if (isset($form[action]) && $form[action] == "search")	{
	$message = "";
	if ( strlen($form[searchstring]) < 3 )
		$message .= "Search string must be at least 3 characters long<br>\n";
	if ( $message == "")	{	// all tests passed
		$starttime = mktime($form[starthour],$form[startmin],0, $form[startmon], 
								$form[startmday], $form[startyear]);
		$endtime = mktime($form[endhour], $form[endmin], 59, $form[endmon], 
								$form[endmday], $form[endyear]);
		
		if ( ! isset( $_GET[orderby] ) )	{
			$_GET[orderby] = "ID";
			$_GET[dirx] = "DESC";
		}
		
		$search = new Search( array("searchstring"=>$form[searchstring], 
							"searchfield"=>$form[searchfield], 
							"start"=>$starttime, 
							"end"=>$endtime, 
							"users"=>$form[users], 
							"genres"=>$form[genres],
							"emphs"=>'', 
							"comp"=>$form[comp], 
							"req"=>$form[req], 
							"fuzzy"=>$form[fuzzy],
							"orderby"=>$_GET[orderby],
							"dirx"=>$_GET[dirx],
							"page"=>$page));
		$success = $search->searchDB();
	}
}
	
?>

<!-- This page generated by Theis Playlist Manager -->
<html>
<head>
<title>Search the playlist database</title>
<link href="wprb.css" rel="stylesheet" type="text/css">
<script language="JavaScript" src="jscripts.js"></script>
</head>
<body>
<?php
if ( $message != "" )
	print "<p><b>$message</b>\n";
?>

<!-- ************ REMOVABLE ************ -->
<?php
include("worldnav.html");
?>
&nbsp;
<p>
<h2>Search the database</h2>
<!-- ********** END REMOVABLE ********** -->

<?php

// PROCESS & DISPLAY SEARCH RESULTS 
if ($success)	{
	$search->reset();
	print "<hr noshade size='1'>\n";
	print "<p><i><b class='black'>Found ".$search->size()." results:</b></i><br>\n";
	if ($search->size() > 0)	{	// results returned
		$headers = array("artist"=>"Artist", "song"=>"Song", 
					"album"=>"Album", "label"=>"Label", 
					"djname"=>"Played by", "starttime"=>"Date");
		print "<table cellpadding='3'>\n";
		print "\t<tr>\n";
		
		$querystring = trimEnd($_SERVER['QUERY_STRING'], "orderby");
		foreach ($headers as $key=>$header)	{
			print "\t\t<th bgcolor='#DDDDDD'><a href=\"search.php?";
			print $querystring ."&orderby=$key";
			if ($_GET[orderby]==$key && $_GET[dirx]=="ASC")
				print "&dirx=DESC";
			else
				print "&dirx=ASC";
			print "\"><b class=\"black\">$header</b></a></th>\n";
		}
		print "\t</tr>\n";
		while ($search->hasNext())	{
			$row = $search->next();
			$insound_artist = urlencode($row->artist);
			$insound_album = urlencode($row->album);
			$insound_label = urlencode($row->label);
			print "\t<tr>\n";
			print "\t\t<td class='mid' bgcolor='#EEEEEE'><a href=\"\" onClick=\"handle_popup('".__ETAIL_ARTIST__."$insound_artist'); return false;\">$row->artist</a></td>\n";
			print "\t\t<td class='mid' bgcolor='#EEEEEE'>$row->song</td>\n";
			print "\t\t<td class='mid' bgcolor='#EEEEEE'><a href=\"\" onClick=\"handle_popup('".__ETAIL_ALBUM__."$insound_album'); return false\">$row->album</a></td>\n";
			print "\t\t<td class='mid' bgcolor='#EEEEEE'><a href=\"\" onClick=\"handle_popup('".__ETAIL_LABEL__."$insound_label'); return false;\">$row->label</td>\n";
			print "\t\t<td class='mid' bgcolor='#EEEEEE'>
				<a href='djplaylists.php?id=$row->userID'>
				$row->djname</a></td>\n";
			print "\t\t<td class='mid' bgcolor='#EEEEEE'>
				<a href='printplaylist.php?show_id=$row->ID'>" .
				date("l, F j, Y, H:i", $row->starttime) . "</a></td>\n";
			print "\t</tr>\n";
		}
		print "</table>\n";
	}
	// add links to next and previous pages of results if there are more than 100
	print "<span class='text'>\n";
	if ( $page > 0 )	{
		$prev_page = $page - 100;
		print "<a href=\"search.php?".$_SERVER['QUERY_STRING']."&page=$prev_page\">prev</a>\n";
	}
	print (( $page > 0 && $search->size() >= 100 ) ? " | " : "" );
	if ( $search->size() >= 100 )	{
		$page += 100;
		print "<a href=\"search.php?".$_SERVER['QUERY_STRING']."&page=$page\">next</a>\n";
	}
	print "</span>\n";
	print "<hr noshade size='1'>\n";
}
?>
<p>

<!-- SEARCH FORM -->
<form method="GET">
<input type="hidden" name="form[action]" value="search">
<input type="hidden" name="page" value="0">
<table border="0" noshade cellpadding="3">
	<tr>
		<td bgcolor="#CCCCCC"><b class='black'>Search by:</b></td>
		<td bgcolor="#CCCCCC"><b class='black'>Search string:</b></td>
		<td colspan="2" bgcolor="#CCCCCC"><b class='black'>Boundary dates:</b></td>
		<td bgcolor="#CCCCCC">&nbsp;</td>
	</tr>
	<tr>
		<td class='norm' bgcolor="#EEEEEE"><select name="form[searchfield]">
			<?php writeSearchOptions($form[searchfield]); ?>
			</select>
		</td><td class='norm' bgcolor="#EEEEEE">
			<input type="text" name="form[searchstring]" value="<?= $form[searchstring] ?>">
		<td class='norm' bgcolor="#EEEEEE"><span class='text'>From:</span> 
			<select name="form[startmon]">
				<?php writeMonthOptions($form[startmon]); ?></select>&nbsp;/&nbsp;
			<select name="form[startmday]">
				<?php writeDayOptions($form[startmday]); ?></select>&nbsp;/&nbsp;
			<select name="form[startyear]">
				<?php writeYearOptions2($form[startyear], $form[startyear]-2003, 1); 
				?></select>&nbsp;&nbsp;
			<div align="right">
			<select name="form[starthour]">
				<?php writeHourOptions($form[starthour]);
				?></select>&nbsp;:&nbsp;
			<select name="form[startmin]">
				<?php writeMinuteOptions($form[startmin]);
				?></select>
			&nbsp;&nbsp;</div>
		</td><td class='norm' bgcolor="#EEEEEE"><span class='text'>To:</span>
			<select name="form[endmon]">
				<?php writeMonthOptions($form[endmon]); ?></select>&nbsp;/&nbsp;
			<select name="form[endmday]">
				<?php writeDayOptions($form[endmday]); ?></select>&nbsp;/&nbsp;
			<select name="form[endyear]">
				<?php writeYearOptions2($form[endyear], $form[endyear]-2003, 1); ?></select>&nbsp;&nbsp;
			<div align="right">
			<select name="form[endhour]">
				<?php writeHourOptions($form[endhour]);
				?></select>&nbsp;:&nbsp;
			<select name="form[endmin]">
				<?php writeMinuteOptions($form[endmin]);
				?></select>
			&nbsp;&nbsp;</div>
		</td>
		<td class='norm' align="right" bgcolor="#EEEEEE"><input type="submit" value="search"></td>
	</tr>
</table>

<!-- SEARCH TYPE -->
<div class='text'>Search type: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
Strict <input type="radio" name="form[fuzzy]" value="0" 
		<?=(! $_GET[form][fuzzy])?"checked":"";?>>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
Fuzzy <input type="radio" name="form[fuzzy]" value="indeed"
		<?=($_GET[form][fuzzy])?"checked":"";?>>
</div>

<!-- SEARCH REFINERS -->
<table cellpadding="3">
	<tr height="50" valign="bottom">
		<td colspan="6"><b class="black">Refine your search:</b></td>
	</tr><tr>
		<td class="norm" bgcolor="#CCCCCC"><b class='black'>dj name(s)</b></td>
		<td class="norm" bgcolor="#CCCCCC"><b class='black'>genre</b></td>
		<td class="norm" bgcolor="#CCCCCC"><b class='black'>compilation</b></td>
		<td class="norm" bgcolor="#CCCCCC"><b class='black'>request</b></td>
	</tr><tr valign="top">
		<td class='norm' bgcolor="#EEEEEE"><select multiple size='5' name="form[users][]">
			<option value=''>all
			<?php writeDJOptions($_GET[form][users][0]); ?></select></td>
		<td class='norm' bgcolor="#EEEEEE"><select multiple name="form[genres][]">
			<option value=''>all
			<?php writeGenreOptions($_GET[form][genres][0]); ?></select></td>
		<td class='norm' bgcolor="#EEEEEE">
			<input name="form[comp]" type="checkbox" value="checked"
				<?=($_GET[form][comp])?"checked":"";?>></td>
		<td class='norm' bgcolor="#EEEEEE">
			<input name="form[req]" type="checkbox" value="checked"
				<?=($_GET[form][req])?"checked":"";?>></td>
	</tr>
</table>
</form>
<p class='text'>
<a style='text-decoration: none' href='' onClick="handle_popup('<?=__ETAIL_LINK__?>'); return false;"><img src='insound.png' alt='support wprb::shop at insound.com' border='0'></a>
</p>
<p class='text'>
<?php
include("worldnav.html")
?>
</p>
</body>
</html>
