<?php
// $Id: login.php,v 1.7 2004/03/12 00:31:46 admin Exp $
/******************************************************************************
 * Theis Playlist Manager -- An interactive web application for creating,     *
 * editing, and publishing radio playlists.                                   *
 *                                                                            *
 * Copyright (C) 2003  Aaron Forrest                                          *
 *                                                                            *
 * This program is free software; you can redistribute it and/or              *
 * modify it under the terms of the GNU General Public License                *
 * as published by the Free Software Foundation; either version 2             *
 * of the License, or (at your option) any later version.                     *
 *                                                                            *
 * This program is distributed in the hope that it will be useful,            *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of             *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              *
 * GNU General Public License for more details.                               *
 *                                                                            *
 * You should have received a copy of the GNU General Public License          *
 * along with this program; if not, write to the Free Software                *
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.*
 *****************************************************************************/

include("lib/config.inc.php");
include("lib/dblib.inc.php");
include("lib/usrlib.inc.php");

// redirect to secure connection
if (! isset($_SERVER['HTTPS']))	{
    header("Location: ".__ROOT__."login.php");
}

$message="";
if ( isset( $_POST[action] ) && $_POST[action] == "login")
 	{
	if ( ! ( $row_array = checkPass( $_POST[login], md5($_POST[password]) )))
		$message .="Incorrect password try again<br>\n";
	if ( $message == "" && $_POST[login] == "admin" ) // start admin session
		{
		cleanMemberSession( $row_array[ID], $row_array[login],
				$row_array[password] );
		header ( "Location: admin/adminmenu.php" );
		}
	if ( $message == "" && $_POST[login] != "admin" ) // start user session
		{
		cleanMemberSession( $row_array[ID], $row_array[login],
				$row_array[password] );
		header ( "Location: user/usermenu.php" );
		}
	}
?>

<html>
<!-- This page generated by Theis Playlist Manager -->
<head>
<title>Login</title>
<link href="css/wprb.css" rel="stylesheet" type="text/css">
</head>
<body>
<table width="100%" height="100%">
 <tr>
  <td align="center" valign="middle">
<table cellpadding="7">
 <tr><td colspan="2">
	<h2 style="text-decoration: underline">Welcome to Theis Playlist Manager</h2>
 </td></tr>
 <tr>
  <td>
<p>
<img width="200" height="200" src="theis.gif" alt="H. Grant Theis">
</p></td>
<td>

<h2>Login</h2>
<?php
if ( $message != "" )
	{
	print "<p><b>$message</b></p>";
	}
?>
<form action="<?= $_SERVER['PHP_SELF'] ?>" method="POST">
<input type="hidden" name="action" value="login">
<input type="hidden" name="<?= session_name() ?>" value="<?= session_id()?>">
<p class='text'>
Login: <br>
<input type="text" name="login" value="<?= $login ?>"><br>
Password: <br>
<input type="password" name="password" value=""><br>
<input type="submit" value="Login">
</form>
</td></tr>
</td></tr></table>
</body>
</html>
